### ISSUE TITLE
Set filename of download

### ISSUE THREAD

**Issue by potatowave** [hardikvasa/google-images-download#106]
**Use Case:** I wanted to download the first result for 800 lines.  Doing so with a four digit prefix created file names such as `0011 1. logo-new.png` where the first 4 digit number is my index, the ` 1. ` is google-images-download's number and then the original filename.

While prefix is available, I wasn't able to find a way to completely set the filename. 

In my scenario I'm iterating through a CSV file and downloading the first result only.  I would like to name that as `0000.jpg` to correspond with the CSV line item. 

Not a big deal to go through and do a bulk re-name, but would be handy to skip this step.  I guess this feature would only be available if limit is set to 1 or give the option for a numbering convention like 0001-001.jpg

To clean up the file names after my download I ran:

```
import glob, os

path =  os.getcwd()
filenames = os.listdir(path)

for filename in filenames:
    split = filename.split('.')

    new = split[0][:-1] + "." + split[-1]
    print new
    os.rename(filename, new)
```

as a separate Python script.

**Comment by hardikvasa** [comment]
@potatowave thanks for the suggestion. Based on the tight integration of iterative naming with the download algo, this feature would mean changes at a lot of different code blocks. And it does not end there...as users would like to have random sequence of numbers or alpha-numbers or completely custom naming, making it difficult for any standard convention.

Adding it in my backlog and closing this issue for now. Thanks!

**Comment by bendae19** [comment]
@potatowave How did you get it to increment from `0000` to `0011` (even if the `1. logo-new.png` stayed? I can't seem to specify the `prefix` setting in a way that is not the exact same for all lines in the csv file...
