### ISSUE TITLE
Permission issue while locating chromeDriver

### ISSUE THREAD

**Issue by nehamjadhav** [hardikvasa/google-images-download#108]
I have successfully downloaded 100 images but gives error while downloading 700 images even after providing chromedriver path.

>>sudo python google_images_download.py -k "NCERT experimental setup" -l 700 -cd /home/neha

Error>>Item no.: 1 --> Item name = NCERT experimental setup
Evaluating...
Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine (exception: Message: 'neha' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
)

**Comment by hardikvasa** [comment]
@nehamjadhav were you able to resolve your issue?

Do take a look at the troubleshooting section of the [docs here](https://github.com/hardikvasa/google-images-download#troubleshooting) for installing necessary chrome browser stable version, etc.

**Comment by hardikvasa** [comment]
Closing this for now. Feel free to re-open the issue if the error still persist.
