### ISSUE TITLE
Chrome version must be >= 65.0.3325.0

### ISSUE THREAD

**Issue by giz02** [hardikvasa/google-images-download#109]
I've downloaded the latest chromedriver but get the following error when trying to evaluate the following command:
googleimagesdownload --keywords "cube" --limit 101 --chromedriver ../chromedriver/chromedriver

Chrome driver is in the path specified:
$ ../chromedriver/chromedriver --version
ChromeDriver 2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb)

And starts
$ ../chromedriver/chromedriver 
Starting ChromeDriver 2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb) on port 9515
Only local connections are allowed.

Evaluating.$ googleimagesdownload --keywords "cube" --limit 101 --chromedriver ../chromedriver/chromedriver

Item no.: 1 --> Item name = cube
Evaluating...
Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine (exception: Message: session not created exception: Chrome version must be >= 65.0.3325.0
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 3.16.0-4-amd64 x86_64)

**Comment by giz02** [comment]
Sorry for the churn - fix was to update google-chrome-stable with latests.  Looks good.

Version of chrome is now:

$ google-chrome-stable --version
Google Chrome 66.0.3359.181 


My misunderstanding was the driver would act independently of the version of chrome-stable installed.

Thanks for a great project - very useful.

**Comment by hardikvasa** [comment]
Thanks @giz02 ! Glad that your issue was resolved.
