### ISSUE TITLE
Problem with 'ś' in query

### ISSUE THREAD

**Issue by piotrex** [hardikvasa/google-images-download#113]
There is a problem with 'ś' character in queries. I had to change some lines in the source code to get script worked properly. I had problem with [str() function](https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20) and [urlib.quote](https://stackoverflow.com/questions/5557849/is-there-a-unicode-ready-substitute-i-can-use-for-urllib-quote-and-urllib-unquot).

**Comment by hardikvasa** [comment]
Closing the issue in favor of PR #114
