### ISSUE TITLE
no_numbering python script

### ISSUE THREAD

**Issue by french1802** [hardikvasa/google-images-download#115]
Hey :)

Doesn't work when the argument is used with a python script : 
arguments = {"keywords" :keyword,"limit":100,"output_directory":photo_folder,"image_directory":dirs,"format":"jpg","no_numbering":True}

neither when the argument default value is set as True directly in the library

I changed the other line of the condition to have my result so it is not an emergency. 

It is still an issue.

Nice work though

**Comment by hardikvasa** [comment]
@french1802 can you check the actual file names on your machine? The terminal might still show numbering just so that the users know how many files are downloaded but the downloaded file names should not have numbering in their names if you have set the `no_number` flag.

do let me know...

**Comment by hardikvasa** [comment]
Closing this issue for now. Let me know if the above comment helped you. Also make sure you have the latest version of this script installed.
