### ISSUE TITLE
use threads for parallel downloads

### ISSUE THREAD

**Issue by kapilkd13** [hardikvasa/google-images-download#117]
Application is great. Everything works fine. Only issue is processing time. It takes a lot of time. Is there a reason threads are not used in this script. Please tell fast, so if it is possible to use threads I will change script and would make a pr updating it.

**Comment by RafaRuiz** [comment]
Please make a PR

**Comment by kapilkd13** [comment]
Yeah, I looked into the code and for mass download it uses selenium and there lies the bottleneck for multi threading. https://stackoverflow.com/questions/30808606/can-selenium-use-multi-threading-in-one-browser 
Although we can run multiple instances of selenium but it has huge memory impacts. Besides I not working with this script anymore.

**Comment by hardikvasa** [comment]
You are right. I did have a couple approaches to dealing with this issue but again each of them have its own drawbacks due to dependencies and would require a major algo overhaul. Adding it to my backlog but closing the issue for now.
