### ISSUE TITLE
chromedriver problem

### ISSUE THREAD

**Issue by Mozhdeh-d** [hardikvasa/google-images-download#120]
Hi,
My chromedriver is installed in /usr/bin and I'm running the following code:
`python3 google_images_download.py -k 'cat' -cd /usr/bin -l 140`

google_images_download.py file's path is: ~/Documents/google-images-download/google_images_download

And the error appears when I run the code:
`Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine (exception: Message: 'bin' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home )`

Any solution?

**Comment by Mozhdeh-d** [comment]
I found the solution here: [https://github.com/hardikvasa/google-images-download/issues/73](url)

**Comment by gjpicker** [comment]
no, I don't think #73  is  a correct answer , if you update or download chromdriver to 2.40   

my experience  is chromdriver <=2.37 work well .so you'd better download/unzip from [driver_2.37](https://chromedriver.storage.googleapis.com/index.html?path=2.37/) again 


`
googleimagesdownload  -k 'example' -l 10000 
`
`
googleimagesdownload  -k 'example' -l 10000  --chromedriver ./chromedriver_2.37
`

ps: you should resolve the dependences of chromedriver_2.37  by youself by `ldd ./chromedriver_2.37`

**Comment by hardikvasa** [comment]
Updated the docs...resolving this issue. Thanks.
