### ISSUE TITLE
list of keywords

### ISSUE THREAD

**Issue by spunknic** [hardikvasa/google-images-download#121]
HI, when I try to use a list like (['car','plane','house']), and execute the  'response.download' func...the system creates the folders but the images doesen´t appear inside, and the console shows a normal downloading process
			
from google_images_download import google_images_download
mixer=['car','plane','house']
for i in mixer:			
	response = google_images_download.googleimagesdownload()
	absolute_image_paths = response.download({'keywords':i,'size':'medium'})

**Comment by hardikvasa** [comment]
@spunknic i will look into reproducing this and revert back with my findings. Thanks.

**Comment by hardikvasa** [comment]
sry for the late response. I tried to repro this issue on my end but was unsuccessful in doing so. It worked just fine for me. Does it timeout or given any error on the download process? Can you try using the limit flag in the config ("limit":5)?

If you can paste the download logs form the terminal, it would be useful.
