### ISSUE TITLE
Downloading only thumbnails

### ISSUE THREAD

**Issue by TheClassyPenguin** [hardikvasa/google-images-download#122]
Is there any way to only download the thumbnails of each image? I am not interested in the full resolution image.

**Comment by hardikvasa** [comment]
@TheClassyPenguin I will consider this as a feature request and add it to my backlog of features to work on. Thanks. It does make up for a perfect use case.

**Comment by haritha-j** [comment]
I was looking for this feature as well, i would really appreciate it if you could implement it / give me some guidance on how to implement it myself. This would be really useful in a lot of scenarios.

**Comment by haritha-j** [comment]
@TheClassyPenguin , if you still need this functionality i implemented some quick changes to a fork of this code over at github.com/haritha-j/google-images-download

This is a very quick fix that breaks the rest of the functionality, but it's enough for my purpose, so it's not at a level of quality where i can submit it as a pull request. But feel free to use the above code if it gets your job done.

**Comment by hardikvasa** [comment]
Thanks @TheClassyPenguin for the issue.

This feature was implemented in https://github.com/hardikvasa/google-images-download/commit/10b8f5b77b2707ee05753c1a73b0938e4a8a2463 . Closing this issue.
