### ISSUE TITLE
Question: How to add the "time" to the metadata

### ISSUE THREAD

**Issue by jimgros** [hardikvasa/google-images-download#124]
I'm interested in knowing when the picture was uploaded/indexed. Would it be possible to add that to the metadata? If so how?
Thanks

**Comment by hardikvasa** [comment]
@jimgros after some looking and trying to find a solution, I think there is no way to extract time the image was indexed in Google. Sad.
closing this issue.

**Comment by jimgros** [comment]
Thanks for trying!
