### ISSUE TITLE
error: argument -s/--size: expected one argument

### ISSUE THREAD

**Issue by Futureknows** [hardikvasa/google-images-download#125]
I am trying to issue googleimagesdownload to download images over 4MP with the following command:

`googleimagesdownload --keywords "stained glass" --limit 200 --size >4MP`

I get the following error code:

`googleimagesdownload: error: argument -s/--size: expected one argument`

**Comment by hardikvasa** [comment]
sorry for the delay in getting back on this. you will need to put the value in quotes so the query should look like this:

`googleimagesdownload --keywords "stained glass" --limit 200 --size ">4MP"`
