### ISSUE TITLE
line 522: why lower()? Creates inconsistency

### ISSUE THREAD

**Issue by jimgros** [hardikvasa/google-images-download#129]
You use lower() for the file name, but it seems that's the only place (you don't use it for the image url).
I'm not sure why you chose to do that, however, this choice creates a disconnect between the URL of the image and the filename the image is saved under.
I think that for consistency purposes might be best to leave the image name as per the URL.
Hope you agree
Thanks.

**Comment by hardikvasa** [comment]
This was resolved a while back. Thanks for pointing it out in first place. Closing this issue. :)
