### ISSUE TITLE
probably an error parsing commandline:

### ISSUE THREAD

**Issue by dmaugis** [hardikvasa/google-images-download#130]
inconssitent behavior with -l

dma:~/Pictures$ googleimagesdownload -k "crepax drawings2" -l 1000

Item no.: 1 --> Item name = crepax drawings2
Evaluating...
Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine (exception: expect bytes or str, not NoneType)
dma:~/Pictures$ googleimagesdownload -k "crepax drawings2" -l 100

Item no.: 1 --> Item name = crepax drawings2
Evaluating...
Starting Download...
Completed Image ====> 1. 3d02632419ac62f521f2b0f9e592c772.jpg
Completed Image ====> 2. luomo-di-pskov---un-uomo-unavventuraby-crepax-guido410967-31227_th.jpg
Completed Image ====> 3. 0be1bb1bcf4fe9246515701123929939--art-lessons.jpg
Completed Image ====> 4. 7e93e8058067ef57bdcb51b5d9d7c7d3--environment-sketch-drawing-things.jpg

**Comment by dmaugis** [comment]
ok - my fault, i should read the doc...but the message is not really explicit, could be "you cannot fetch more than 100 images without installing chome/chromedriver"

**Comment by hardikvasa** [comment]
Updated the docs...resolving this issue. Thanks.
