### ISSUE TITLE
how to set the filename with the search keyword

### ISSUE THREAD

**Issue by leejoonsung007** [hardikvasa/google-images-download#134]
It seems that the filename is generated from the IMG URL, how to rename the file with the keyword input?

response = google_images_download.googleimagesdownload()
arguments = {"keywords":"cat, dog", "limit":1, "print_urls":True, "image_directory":'home1', "size":"large"} 

Item no.: 1 --> Item name = cat
Evaluating...
Starting Download...
Image URL: https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03.jpg
Completed Image ====> 1. 1200px-cat03.jpg
**Expected filename**: cat.jpg
Errors: 0

Item no.: 2 --> Item name =  dog
Evaluating...
Starting Download...
Image URL: https://i.ytimg.com/vi/SfLV8hD7zX4/maxresdefault.jpg
Completed Image ====> 1. maxresdefault.jpg
**Expected filename**: dog.jpg
Errors: 0

**Comment by Ginzry** [comment]
any answers was commited in this question?

**Comment by Amalsarr** [comment]
any answers ?

**Comment by NicolasGrosjean** [comment]
You have [input arguments](https://google-images-download.readthedocs.io/en/latest/arguments.html) to set prefix, suffix and/or numbering to file names.

If you want other way to name the result images, you can edit code.

```python
if no_numbering:
    path = main_directory + "/" + dir_name + "/" + prefix + image_name
else:
    path = main_directory + "/" + dir_name + "/" + prefix + str(count) + "." + image_name

try:
    output_file = open(path, 'wb')
```

[Source](https://github.com/Joeclinton1/google-images-download/blob/patch-1/google_images_download/google_images_download.py#L775)
