### ISSUE TITLE
Multiple file format in a single request

### ISSUE THREAD

**Issue by fstinner** [hardikvasa/google-images-download#136]
It's probably more of a feature request. If you search for certain terms and only want results in certain file formats (e.g. jpg, png, svg), only one file format can be specified. Google can only use one format too, but it may be possible to use different file extensions. E.g. by an iterating search over the formats.

**Comment by manjrekarom** [comment]
I want this particular feature too. If you there's no problem can I take up this issue?

**Comment by hardikvasa** [comment]
This was requested before in #57 . @manjrekarom sure. How do you propose including this feature? When a user specifies 10 images to be downloaded for example, should it be 10 for each format specified or 10 overall?

**Comment by manjrekarom** [comment]
Hi @hardikvasa,
It will be 10 overall with either of the formats in the list provided as an argument. 

Also, I saw #57. I see you had proposed a similar thing there. Are there a lot of places where these changes might need to be propagated?

**Comment by hardikvasa** [comment]
After some search I realized that this will not fix. There is no way to specify more than one image in the URL and hence as mentioned in #57 will need to be done via config file.
