### ISSUE TITLE
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>

### ISSUE THREAD

**Issue by patrickluvsoj** [hardikvasa/google-images-download#140]
First of all, great tool! I'm using for the Fast.ai course to get some images. Encountered the following error when using it in another laptop after successfully running it in another (both macs). Apparently on Python 3.6 and 3.7 certificates are not installed you need install separately. Maybe something to document unless this is just something standard that I missed setting-up: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

googleimagesdownload --keywords "baloons" -l 10

Item no.: 1 --> Item name = baloons
Evaluating...
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>
Starting Download...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/googleimagesdownload", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 888, in main
    paths = response.download(arguments)  #wrapping response in a variable just for consistency
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 843, in download
    items,errorCount,abs_path = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 695, in _get_all_items
    object, end_content = self._get_next_item(page)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google_images_download/google_images_download.py", line 660, in _get_next_item
    start_line = s.find('rg_meta notranslate')
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by daolq3012** [comment]
@patrickluvsoj 
> This is sloved my problem..
```
cd /Applications/Python\ 3.7/
./Install\ Certificates.command
```
ref: https://github.com/slackapi/python-slackclient/issues/334#issuecomment-433498349

**Comment by hardikvasa** [comment]
@daolq3012 thanks for the comment. I will add this in the docs within the troubleshooting section.

**Comment by hardikvasa** [comment]
Added to the [docs](https://google-images-download.readthedocs.io/en/latest/troubleshooting.html#urlopen-error-ssl-certificate-verify-failed)

closing this issue as it is external to the library.

**Comment by ghost** [comment]
On Ubuntu, this worked for me.

$ sudo update-ca-certificates --fresh
$ export SSL_CERT_DIR=/etc/ssl/certs

**Comment by abhijitmjj** [comment]
> On Ubuntu, this worked for me.
> 
> $ sudo update-ca-certificates --fresh
> $ export SSL_CERT_DIR=/etc/ssl/certs

This worked!

**Comment by avanibhatnagar** [comment]
How to solve this error on Windows?
