### ISSUE TITLE
Hi,Why always '0 is all we got for this search filter!'

### ISSUE THREAD

**Issue by lionnner** [hardikvasa/google-images-download#141]
<img width="811" alt="886a731d-c1e1-4eae-bdf0-791dd866df8b" src="https://user-images.githubusercontent.com/19425203/43940794-e42274a0-9ca3-11e8-8477-c28685d098fc.png">

**Comment by lionnner** [comment]
it's my issuse,

**Comment by Jayshine** [comment]
I have the same question. So why? Please

**Comment by lionnner** [comment]
Because your Terminal App couldn't connect to google.com.
