### ISSUE TITLE
 Error keywords encode 

### ISSUE THREAD

**Issue by elicec** [hardikvasa/google-images-download#142]
Cool tool，thanks.
I use the json config file with Chinese (Simplified)
"Records": [
        {
            "keywords": "壁纸",
            "limit": 10,
            "color": "green",
            "print_urls": true
        }
    ]

But the keywords become '澹佺焊'

**Comment by elicec** [comment]
i solve it

**Comment by CookingBoy** [comment]
emmm请问一下google爬图片是不是要翻墙

**Comment by elicec** [comment]
当然，这个项目可以设置代理。




------------------ 原始邮件 ------------------
发件人: "CookingBoy"<notifications@github.com>;
发送时间: 2018年8月26日(星期天) 上午8:52
收件人: "hardikvasa/google-images-download"<google-images-download@noreply.github.com>;
抄送: "彭红"<elicec@foxmail.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [hardikvasa/google-images-download]  Error keywords encode (#142)




emmm请问一下google爬图片是不是要翻墙
