### ISSUE TITLE
How to add further specifications?

### ISSUE THREAD

**Issue by gdorai** [hardikvasa/google-images-download#15]
If I want to filter only the images that are "Labeled for Reuse", then, how do I specify it in the code? (tools -> usage rights -> labeled for reuse).

**Comment by rachmadaniHaryono** [comment]
just as a note for this problem:

i found query for the option as following

```
normal
https://www.google.com/search?q=keyword1&[...]&tbs=imgo:1&[...]
reuse with modification
https://www.google.com/search?q=keyword1&[...]&tbs=imgo:1,sur:fmc&[...]
reuse
https://www.google.com/search?q=keyword1&[...]&tbs=imgo:1,sur:fc&[...]
non comercial reuse with modification
https://www.google.com/search?q=keyword1&[...]&tbs=imgo:1,sur:fm&[...]
non commercial reuse
https://www.google.com/search?q=keyword1&[...]&tbs=imgo:1,sur:f&[...]
```

**Comment by hardikvasa** [comment]
Thanks for bringing this up.
Specifications have been added including usage rights, time, size, type of image and color.
Resolving this issue.
