### ISSUE TITLE
Contact detail scrape

### ISSUE THREAD

**Issue by Arena100** [hardikvasa/google-images-download#157]
Hi Guys - brilliant tool that I have used frequently, this has saved me copious amount of time. I wonder if the code can be modified to scrape contact details rather than images based on a given list, i.e (image attached)

![capture](https://user-images.githubusercontent.com/13103024/45357163-5556d300-b5bd-11e8-9716-644a666c232d.JPG)

**Comment by hardikvasa** [comment]
@Arena100 thanks for your comment. Glad to know you are liking the script. Unfortunately for now this script is dedicated to just downloading images. You should look for [beautifulsoup4](https://pypi.org/project/beautifulsoup4/) for parsing HTML elements.

Closing this issue.
