### ISSUE TITLE
Error: Looks like we cannot locate the path the 'chromedriver'

### ISSUE THREAD

**Issue by lbenassi** [hardikvasa/google-images-download#159]
Hi,
I try this tool and is very usefull, but I encountered a problem.
This is my simple code to download images related to tables:
`from google_images_download import google_images_download
response = google_images_download.googleimagesdownload()
arguments =  {"keywords":"Table","limit":100,"print_urls":False,"output_directory":myDir}
paths = response.download(arguments)`

When I imposed `"limit":100` the code works correctly, but if I impose `"limit":200` the code returns me the following error:

**Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine (exception: argument of type 'NoneType' is not iterable)**

I checked the search query on google and returned many more than 200 images.
Has anyone had the same problem and knows how to solve it? 
Thanks in advance

**Comment by ahmed-bensaad** [comment]
Got the same error over here. Any solutions?

**Comment by devajith** [comment]
According to the documentation  : If you would want more than 100 images per keyword, then you would need to install Selenium library along with chromedriver.

**Comment by hardikvasa** [comment]
@lbenassi @ahmed-bensaad as per the above comment from @devajith you will need to use the chromedriver flag and specify the path of the driver. All the details are in the documentation.

Closing this issue.

**Comment by nicejava** [comment]
Use chormedriver 80 so will solved this problem 
https://chromedriver.storage.googleapis.com/index.html?path=80.0.3987.106/

eg. When i extract chormedriver exe to chromedriver_win32-80
    
    chromedriver = "chromedriver_win32-80/chromedriver.exe"
    response = google_images_download.googleimagesdownload()
    response.download({
        "keywords": "portrait transparent background",
        "color_type": "transparent",
        "size": "medium",
        "limit": 500,
        "output_directory": output_dir,
        "chromedriver": chromedriver})
