### ISSUE TITLE
Won't work for Python 3.6

### ISSUE THREAD

**Issue by Jaunter** [hardikvasa/google-images-download#16]
Urllib2 is deprecated and urllib.request.Request doesn´t exist.
Thank you.

**Comment by rachmadaniHaryono** [comment]
Hi @Jaunter, we made python 3 fork at @rytoj. You can try it and sed if it meet your requirements

**Comment by Jaunter** [comment]
Fine, thank you!!

**Comment by hardikvasa** [comment]
fixed it in this repo. Thanks for identifying.
