### ISSUE TITLE
How to set output image name 

### ISSUE THREAD

**Issue by shanalikhan** [hardikvasa/google-images-download#160]
I want to generate images as :

 > df_{number}.jpg

Where the `{number}` is the download index.

How to do that?

Currently it downloads as following:

![image](https://user-images.githubusercontent.com/8774556/45551930-c231cd80-b848-11e8-82bd-412c07db8c4b.png)

**Comment by dawnknight** [comment]
I think one quick way is that you can modify line 601 in google_image_download.py to 
path = main_directory + "/" + dir_name + "/" + prefix + str(count).zfill(6) + ".jpg"
then the output file name will be the download order number

**Comment by hardikvasa** [comment]
this can be achieved using the --prefix or -pr option. More info in the readme file.
