### ISSUE TITLE
Downloading random images

### ISSUE THREAD

**Issue by ekosman** [hardikvasa/google-images-download#162]
I want to download random images every time I search.
Is this currently possible?

**Comment by hardikvasa** [comment]
@ekosman this would be a good feature to have. But with the current implementation, the images are downloaded one by one as the script finds new links. This saves a lot of initialization time. 

With that being said, I have a way to workaround this situation to have random images downloaded.

**Comment by hardikvasa** [comment]
Closing this issue for now. I have added this to my backlog and I will get to this a little later. Thanks for the feature request though.
