### ISSUE TITLE
clip-art type parameter changed

### ISSUE THREAD

**Issue by ezavesky** [hardikvasa/google-images-download#171]
Looks like the type specification parameter (in the query) for 'clip-art' has changed from 'clip-art' to 'clipart'.  Should be an easy fix around [this line](https://github.com/hardikvasa/google-images-download/blob/master/google_images_download/google_images_download.py#L383).  Thanks for making the nice tool!

**Comment by hardikvasa** [comment]
@ezavesky thanks for pointing this out. The issue was fixed in #172 . Closing this issue.
