### ISSUE TITLE
How can i get next 100 data?

### ISSUE THREAD

**Issue by kkhzz1004** [hardikvasa/google-images-download#178]
hi guys, this is awesome project
i just wonder if i get 100 data(maybe from first page).
how can i get next 100 data(like from next page or specific page).
anyone knows this?

**Comment by loaiibnka3b6** [comment]
i have the same question here what if i nedd more than 100 images

**Comment by hardikvasa** [comment]
@kkhzz1004 @clem9669 
yes all the instructions are in the readme file. Let me know if you have any other questions.
