### ISSUE TITLE
image url only

### ISSUE THREAD

**Issue by albertusgeyser** [hardikvasa/google-images-download#179]
Good Day 

Received that feature implemented, but need some help to retrieve url.

My current code:

response = google_images_download.googleimagesdownload()
	arguments = {"keywords": str(code),"limit":1,"no_download":True}
	paths = response.download(arguments)
	print(paths)

how can i add url to a variable?
url = paths

Hope anyone could help as my string give: {'Code': [None]}

Thank You

Albertus Geyser

**Comment by albertusgeyser** [comment]
Could anyone help to inform me how i can only get image url for images?

Thank You

Albertus Geyser

**Comment by hellogan** [comment]
Hey Albertus - I just made a PR to fix this, you should be able to see the link above and monitor the change's status there.

**Comment by albertusgeyser** [comment]
Good Day 

Thank you for code.

Is this change? as i change it to do test, but not sure if correct:

# Download Images
    def download_image(self,image_url,image_format,main_directory,dir_name,count,print_urls,socket_timeout,prefix,print_size,no_numbering,no_download):
        if print_urls or no_download:
            print("Image URL: " + image_url)
        if no_download:
            return "success","Printed url without downloading",None,**image_url**
        try:

**Comment by hellogan** [comment]
Yep, that looks like the change I made. So changing the code to that locally should work until the change is merged in to the master branch. (Just make sure you remove the *s)

**Comment by hardikvasa** [comment]
closing as the original issue seems to be resolved.
