### ISSUE TITLE
Format type filter gather files with wrong extension

### ISSUE THREAD

**Issue by savardmario** [hardikvasa/google-images-download#183]
I used version 2.5.0 with the following command: python google_images_download.py --keywords "clown" --format "png" --limit 15 --size medium

I do get .jpg even if I specified "png" as requested format. I would expect to receive only png files.

Completed Image ====> 1. aj5chhqwc308cw7ja9d0.png
Completed Image ====> 2. pennywise.png
Completed Image ====> 3. ronald-mcdonald-clown-hed-a-2016.png
Completed Image ====> 4. 141031122838-elam-creepy-clown-copycats-go-global-02-story-top.png
Completed Image ====> 5. clowns-hero-1.png
Completed Image ====> 6. https%3a%2f%2fblueprint-api-production.s3.amazonaws.com%2fuploads%2fstory%2fthumbnail%2f23903%2fscreen_shot_2016-10-10_at_3.53.24_pm.png
Completed Image ====> 7. gummo_the_clown_front_7.png
Completed Image ====> 8. pennywise_the_dancing_clown.png
Completed Image ====> 9. 4c29b7b75ba38c9c498fdc0c27c84aca.png
Completed Image ====> 10. thumb.png
Completed Image ====> 11. creepy-clown.png
Completed Image ====> 12. 141031122927-elam-creepy-clown-copycats-go-global-03-story-top.png
Completed Image ====> 13. clowns_0.png
Completed Image ====> 14. 2016-10-11_opi_25389998_i1.jpg
Completed Image ====> 15. clown-1475762369-640x356.png

**Comment by savardmario** [comment]
I pushed more the investigation and it seems related to the fact that PNG images are wrongly named "jpg". Maybe the file extension should be enforced. For instance, if requesting PNG, jpg file extension should be renamed .png instead of letting .jpg.

**Comment by hardikvasa** [comment]
This is now resolved in https://github.com/hardikvasa/google-images-download/commit/cf5ff4876b8384ef0d92e68b66fa648e494d2640

closing this issue for now. If the issue still persist, feel free to reopen this thread.
