### ISSUE TITLE
Adding an option to exclude a website

### ISSUE THREAD

**Issue by yairhasfari** [hardikvasa/google-images-download#187]
Can you add an option to exclude a specific website from the search?
for example, when searching google i can usually add : "-site:https://wikipedia.com" and results will exclude images from that website

**Comment by blairly** [comment]
I've submitted a PR with this feature added, pending merge:
https://github.com/hardikvasa/google-images-download/pull/195

**Comment by hardikvasa** [comment]
Awaiting some corrections on #213 before it can be merged.

**Comment by hardikvasa** [comment]
This feature was merged, closing this issue. I will update the docs soon to reflect the changes.
