### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by pixelnull** [hardikvasa/google-images-download#199]
I am using this library to return the URL only and used the solution in issue #179 for that. Which works well, thank you for making it.

Is there a not too involved edit I can do to stop the print outputs? i.e. get rid of this:

> Item no.: 1 --> Item name = text
Evaluating...
Starting to Print Image URLS
Image URL: https://url
Printed url without downloading

**Comment by hardikvasa** [comment]
@pixelnull i like the idea to have a silent mode. It would make a good feature.
currently it would be tricky as it would mean you will have to remove multiple print statements from various places.

**Comment by marian-code** [comment]
There is a super easy way to do this, with use of contextlib. But it is rather a workaround than a good long therm solution. Just use this:
`from contextlib import redirect_stdout`
than wrap the call to main() with it.
``` python
f = io.StringIO()
with redirect_stdout(f):
    main()
```
Here is the link do docs: https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout

**Comment by hardikvasa** [comment]
This was natively integrated in https://github.com/hardikvasa/google-images-download/commit/10b8f5b77b2707ee05753c1a73b0938e4a8a2463 . Closing the issue.
