### ISSUE TITLE
Any idea why the script is damn slow?

### ISSUE THREAD

**Issue by JafferWilson** [hardikvasa/google-images-download#20]
I am trying to play with your script and found it damn slow. Even the code doesn't work with Python 3.5 only.
Any idea how I can make the script work faster, please let me know

**Comment by rachmadaniHaryono** [comment]
>Even the code doesn't work with Python 3.5 only

there is pr for python3 compatibily here #13 

>Any idea how I can make the script work faster, please let me know

use pool or async, e.g. http://shawnmehan.com/async-or-threaded-file-downloads-in-python-3-x/

**Comment by JafferWilson** [comment]
> use pool or async, e.g. http://shawnmehan.com/async-or-threaded-file-downloads-in-python-3-x/
If I am using python 2.7 then is there any thread for it too?

**Comment by JafferWilson** [comment]
And can you show me how I can use the library what you have specified in the above link with the code of this repository?

**Comment by rachmadaniHaryono** [comment]
Async isn't available on python 2.7, so only pool is possible. Related : 

- https://stackoverflow.com/questions/1239035/asynchronous-method-call-in-python
- https://docs.python.org/2/library/multiprocessing.html


>And can you show me how I can use the library what you have specified in the above link with the code of this repository?

Edit around this line

https://github.com/hardikvasa/google-images-download/blob/master/google-images-download.py#L143

**Comment by JafferWilson** [comment]
Thank you very much.
