### ISSUE TITLE
Anyone found a way to avoid the watermarked images? (getty, stock, etc.?)

### ISSUE THREAD

**Issue by NanoMeko** [hardikvasa/google-images-download#201]
When I download a bunch of images, a large number of them come from sources where the actual google preview image has watermarks. Anyway to avoid this? I understand that it's to protect IP but for research purposes and since sometimes non-watermarked images are available after clicking through, is there a flag for avoiding or skipping those images?

**Comment by clem9669** [comment]
I don't see for my perspective any way to do that :(

**Comment by krissdap** [comment]
I guess you could try maintaining a list of domain that you would not want an image from.
E.g. https://media.gettyimages.com/

**Comment by hardikvasa** [comment]
@NanoMeko the images are retrieved from the URL that the search provides and hence it is not possible to gather images without watermarks. I will look into the PR for blacklisting domains so you can avoid URLs that commonly have watermarks as @krissdap suggested :)
