### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by phyogesh** [hardikvasa/google-images-download#208]
Hello,
I am very very new to python coding and using Jupyter hub notebook. I am getting syntax error for the following code, any thoughts on how to correct:

!pip install google_images_download

import google_images_download
googleimagedownload --keywords "car" --limit 2

File "<ipython-input-62-37bb38122467>", line 2
    googleimagedownload --keywords "car" --limit 2
                                                                       ^
SyntaxError: invalid syntax

**Comment by Naman-Garg-06** [comment]
I think this is a command line python program as mentioned in the readme. Also while running this command in terminal, it is giving correct results.

**Comment by phyogesh** [comment]
Thank you!
