### ISSUE TITLE
Passing the json config file through a script, no example of function

### ISSUE THREAD

**Issue by sorathesky** [hardikvasa/google-images-download#211]
I'm trying to use this as a way to download images for an ML script. The one thing I don't get is why this is not working.

> response = gid.googleimagesdownload()
arguments = {"config_file": "example.json"}
paths = response.download(arguments)

I can't seem to get it to work following the convention of the example you set.

> Uh oh! Keywords is a required argument 
Please refer to the documentation on guide to writing queries 
https://github.com/hardikvasa/google-images-download#examples

It passes this but I makes no sense since you have to have the keyword inside the json file and it would make no sense to set keyword: example.json and then config_file: example.json.

can anyone help me understand this?

**Comment by hardikvasa** [comment]
@sorathesky This is a missing feature. When `config_file` feature was added, it was only for command line interface commands and not for imports. I am am planning to added this sometime soon.

**Comment by hardikvasa** [comment]
@sorathesky this feature was added in https://github.com/hardikvasa/google-images-download/commit/10b8f5b77b2707ee05753c1a73b0938e4a8a2463 . Let me know if you still see issues with it. Closing the issue for now.
