### ISSUE TITLE
Chrome driver should respect proxy setting

### ISSUE THREAD

**Issue by SuJiKiNen** [hardikvasa/google-images-download#215]
On Windows,`http_proxy` environment variable not works for driver.

**Comment by hardikvasa** [comment]
@SuJiKiNen did you try the proxy argument of the library? More information in the README file.

**Comment by SuJiKiNen** [comment]
@hardikvasa I tired,the Chrome driver has a proxy option,how about explicit pass proxy setting to it?

**Comment by hardikvasa** [comment]
@SuJiKiNen chromdriver proxy option was not used because not all cases require you to use chromedriver. When you are not downloading bulk images chromedriver is not in use. Did --proxy setting work for you?

**Comment by SuJiKiNen** [comment]
@hardikvasa I am not sure,It's been a long time, and I was downloading the bulk images, and it failed to respect proxy setting, sorry for this.I forgot to mention it.

**Comment by hardikvasa** [comment]
no worries at all. closing this issue for now. Do update this thread if you still see the issue when using proxy arg. I have tried it on my end and proxy seems to be working as expected.
