### ISSUE TITLE
php files galore

### ISSUE THREAD

**Issue by sq5rix** [hardikvasa/google-images-download#231]
Hi! 
Thank you for excellent library!!
I have a following query in my python file:
absolute_image_paths = response.download(arguments = {"keywords":'"'+ line + '"',
                                            "output_directory":BUG_DIR,
                                            "image_directory":words[1],
                                            "size":"large",
                                            "format":"jpg",
                                            "limit":LIMIT,
                                            "print_urls":False} )

Everything works great, only minor problem - I get a lot of useless php files, like "8. showimg.php"

Is it some way to stop them? Or, am I doing something wrong?

**Comment by hardikvasa** [comment]
@sq5rix getting some images other than what you have specified in `"format"` param is a known issue which I am trying to resolve. Can you give me one or more of the complete keywords that you used which resulted in the mentioned behavior? That will help me in troubleshooting the issue further.

**Comment by sq5rix** [comment]
Hi!
Here you go. It is a search which takes lines from text file, I attached head of the file 

https://gist.github.com/sq5rix/6dc81e5819df3ba542868c4ae0879905

I noticed that if I ask to save a picture url, I get less php files 

Greetings,
Tom

**Comment by hardikvasa** [comment]
Thanks! I will check this out soon.

**Comment by hardikvasa** [comment]
Some changes were made to the algo in https://github.com/hardikvasa/google-images-download/commit/cf5ff4876b8384ef0d92e68b66fa648e494d2640 . Can you try again and let me know if this works as expected now?

**Comment by sq5rix** [comment]
Hi!
I run again with new code. 
I report no errors
Great job!!
