### ISSUE TITLE
FileNotFound for sample_config.json

### ISSUE THREAD

**Issue by hollandasa** [hardikvasa/google-images-download#237]
Hi all,

Non-programmer here, so I'd appreciate any help you guys could provide. I have created a config file using Notepad++ and saved it as a .json file within the same directory as the google_images_download file. I attempted to run using cmd within the googleimagesdownload program, but my attempt gave me the error "No such file or directory." 

Figuring I made a mistake, I attempted to import the pre-existing sample config file 'sample_config.json' file inside the "\google-images-download-master\google-images-download-master\google_images_download" folder by entering to run "googleimagesdownload -cf sample_config.json, but received the same error.

![image](https://user-images.githubusercontent.com/28410688/57581402-ed8bbb80-74ae-11e9-8926-3102848bfec9.png)

Can anyone provide some pointers? Any help would be appreciated!

Cheers,
Asa

**Comment by hardikvasa** [comment]
`googleimagesdownload` is an executable which is not where you have installed your library. The `sample_config.json` should be in the directory from where you are running this command "C:\Users\Asa" .

**Comment by hollandasa** [comment]
Brilliant! Thank you very much for replying! I knew it was a stupid mistake on my part.
Loaded my config file properly and am now successfully downloading images. Many, many thanks.

**Comment by hardikvasa** [comment]
Happy to help!
