### ISSUE TITLE
Improper file format naming.

### ISSUE THREAD

**Issue by skipz36** [hardikvasa/google-images-download#24]
### All images are treated as a jpg, if a non-jpg file is downloaded, it will be given the wrong file format.

**Comment by rachmadaniHaryono** [comment]
hi @skipz36 , can you try @rytoj fork https://github.com/rytoj/google-images-download.

there the target filename is not forced to have jpeg extension and there is also sha256 filename mode, to keep the image file unique

**Comment by hardikvasa** [comment]
Thanks @rachmadaniHaryono for all the wonderful updates post fork. Great work!

**Comment by hardikvasa** [comment]
The script now downloads images with the correct file format and by using the original name of the image.
