### ISSUE TITLE
Feature Request: Download History to Avoid Redownloading

### ISSUE THREAD

**Issue by tjysdsg** [hardikvasa/google-images-download#249]
Recently I worked on a project that needs to download tons of images. However, I found it inconvenient when I pause the crawler and rerun it, google-images-download would download all the images again. So I can only modify the file containing the keywords (delete the downloaded entries) to avoid that. I think it may be great if this tool can remember downloading history?

**Comment by jithinlalk25** [comment]
Good suggestion. I would like to implement this feature.
