### ISSUE TITLE
name 'request' is not defined

### ISSUE THREAD

**Issue by fadhil207** [hardikvasa/google-images-download#26]
name 'request' is not defined                          
[2018-01-17 06:11:18.374911] [ INFO ] ERROR : 'NoneType
' object has no attribute 'find'

elif cmd.startswith("image "):
                            sep = msg.text.split(" ")
                            search = msg.text.replace(sep[0] + " ","")
                            url = 'https://www.google.com/search?hl=en&biw=1366&bih=659&tbm=isch&sa=1&ei=vSD9WYimHMWHvQTg_53IDw&q=' + urllib.parse.quote(search)
                            raw_html = (download_page(url))
                            items = []
                            items = items + (_images_get_all_items(raw_html))
                            path = random.choice(items)
                            try:
                                start = timeit.timeit()
                                client.sendImageWithURL(to,path)
                  #  wb1.sendMessage(msg.to, "「Google Image」\nType: Search Image\nTime taken: %s" % (start) +"\nTotal Image Links = "+str(len(items)))
                            except Exception as e:
                                client.sendMessage(to, str(e))

**Comment by rachmadaniHaryono** [comment]
Run `pip install requests`

**Comment by hardikvasa** [comment]
did that help @fadhil207 ? Closing this issue for now.

**Comment by fadhil207** [comment]
not yet , no atribute find ! 🙄🙄

**Comment by rachmadaniHaryono** [comment]
can you post full error?
