### ISSUE TITLE
unrecongized arguments

### ISSUE THREAD

**Issue by BLCKPSTV** [hardikvasa/google-images-download#27]
When running the example I get following error on ubuntu 17.10

`google-images-download.py: error: unrecognized arguments: Polar bears, baloons, Beaches 20
`

**Comment by rachmadaniHaryono** [comment]
do you put the quote character there (`"`)? the program may recognize the following words as argument.

**Comment by hardikvasa** [comment]
Most of the command line tools separate arguments using space character. If your argument has space in it, you must wrap it in quotes as @rachmadaniHaryono mentioned.
