### ISSUE TITLE
When doing silent_mode and no_download, message is still printed.

### ISSUE THREAD

**Issue by hollowgalaxy** [hardikvasa/google-images-download#276]
I get 
```
Downloading images for: 2019-10-19 19_19_06 ...
https/url-path-here.com/this-is-not-real.png
```
repeatedly.
[This](https://github.com/hardikvasa/google-images-download/blob/0d2bf8f17b5a8806d90df7258e7a172aa0cb7963/google_images_download/google_images_download.py#L925) prints `Downloading images...`
[This](https://github.com/hardikvasa/google-images-download/blob/0d2bf8f17b5a8806d90df7258e7a172aa0cb7963/google_images_download/google_images_download.py#L428) prints the url

I would assume with silent_mode there should not be a `Downloading images...`
And the urls should only be printed if print_urls flag is set.

For additional debug information. I'm installing with `pip install git+repo_name` and using python to run the module

**Comment by imanvanassum** [comment]
`
parser.add_argument('-nd', '--no_download', default=False, help="Prints the URLs of the images and/or thumbnails without downloading them", action="store_true")
`

Looks like silent mode does not suppress the no_download behaviour.

**Comment by imanvanassum** [comment]
https://github.com/hardikvasa/google-images-download/pull/283
