### ISSUE TITLE
No module named 'google_images_download'

### ISSUE THREAD

**Issue by NicolasMICAUX** [hardikvasa/google-images-download#339]
Hi, after installing with pip i get error :
`
from google_images_download import google_images_download
ModuleNotFoundError: No module named 'google_images_download'
`
pip was sucessful :
`
Successfully built google-images-download
Installing collected packages: selenium, google-images-download
Successfully installed google-images-download-2.8.0 selenium-3.141.0

`
Any idea why ?

**Comment by hyusap** [comment]
What command do you use to run your python file?

**Comment by NicolasMICAUX** [comment]
ran with Pycharm, and installed module with pycharm also

**Comment by NicolasMICAUX** [comment]
thx for your answer

**Comment by hyusap** [comment]
are you using a pycharm virtualenv? not the best solution but it can help.

**Comment by NicolasMICAUX** [comment]
I was already using it. Ok, seems it's unrelated, I recreated a venv and it works. Thx for all !

**Comment by JoeDesylva** [comment]
#352
