### ISSUE TITLE
Error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by MFrat** [hardikvasa/google-images-download#34]
IOError on an image...trying next one... Error: [Errno 2] No such file or directory: 'downloads/myQuery /1

Ex:
Starting Download...
IOError on an image...trying next one... Error: [Errno 2] No such file or directory: 'downloads/Polar bears /1. 220px-Polar_Bear_-_Alaska_%28cropped%29.jpg'
IOError on an image...trying next one... Error: [Errno 2] No such file or directory: 'downloads/Polar bears /1. edu-center-D00002331.jpg'
IOError on an image...trying next one... Error: [Errno 2] No such file or directory: 'downloads/Polar bears /1. Medium_WW22786.jpg'
IOError on an image...trying next one... Error: [Errno 2] No such file or directory: 'downloads/Polar bears /1. Original_WW215278.jpg'
IOError on an image...trying next one... Error: [Errno 2] No such file or directory: 'downloads/Polar bears /1. skynews-polar-bears-arctic_4130795.jpg'
IOError on an image...trying next one... Error: [Errno 2] No such file or directory: 'downloads/Polar bears /1. Facts-about-polar-bears-5.jpg'
IOError on an image...trying next one... Error: [Errno 2] No such file or directory: 'downloads/Polar bears /1. ct_110915-23.jpg'
IOError on an image...trying next one... Error: [Errno 2] No such file or directory: 'downloads/Polar bears /1. 162652-004-34A1BA10.jpg'
IOError on an image...trying next one... Error: [Errno 2] No such file or directory: 'downloads/Polar bears /1. polar-bear-help-604mk101612-604-337-7b6e7b90.rendition.598.336.jpg'
IOError on an image...trying next one... Error: [Errno 2] No such file or directory: 'downloads/Polar bears /1. 6375873931_9046c0c779_b-1024x738.jpg'

Happening on Windows and Linux.

**Comment by agustinmorantes** [comment]
Same issue here

**Comment by hardikvasa** [comment]
Can you please post the command line query?

**Comment by hardikvasa** [comment]
@MFrat , @agustinmorantes the bug had now been resolved. Do let me know if you still see this as an issue in Windows OS. Closing this for now.

**Comment by MFrat** [comment]
@hardikvasa, working now, thanks!
