### ISSUE TITLE
Error when using chromedriver

### ISSUE THREAD

**Issue by wying8349** [hardikvasa/google-images-download#355]
Hi, I have an error when using Chromedriver. It reports:
```[0915/110330.522:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader```
What might the problem be? Thank you very much.

**Comment by NicolasGrosjean** [comment]
It seems related to Chromedriver and not specifically to the usage of Chromedriver with this project.

You should take a look on [Stackoverflow](https://www.google.com/search?q=Passthrough+is+not+supported,+GL+is+swiftshader+site:stackoverflow.com) if a given answer solves your issue.
