### ISSUE TITLE
How to download more images?

### ISSUE THREAD

**Issue by LongLong-Jing** [hardikvasa/google-images-download#4]
@hardikvasa 
Hi Hardikvasa, thanks for your work. I have a question about downloading the images. What can I do if I want to download more images ? Specifically, What should I do if I want to download all the images under the keywork "Taj Mahal" ? Thanks for your help.

**Comment by hardikvasa** [comment]
Hi LongLong-Jing@
The current script downloads all the images (100) in the first page of google images search result. For downloading more than 100 images, you will have to refine your search and add more search terms in the array.

Note: Please do go through the Disclaimer notice in the README file of this repository before downloading and using the images.

**Comment by sunshineatnoon** [comment]
@hardikvasa  Thanks for this great script. May I ask how to download more than 100 images for a single search keyword?

**Comment by hardikvasa** [comment]
Hi, as of now there is no 'direct' way to download more than 100 images from a single keyword since the response receives a max of 100 results. The best way to do that would be to add more keywords/key phrases and broaden the scope of search.

Thanks!

**Comment by sunshineatnoon** [comment]
@hardikvasa Thanks for the reply.
FYI, one potential way to solve this issue is to set time limitations, so that one can crawl 1000 images in each time interval.

**Comment by hardikvasa** [comment]
Hi @sunshineatnoon 
Every time a a page is downloaded (based on a given keyword), the crawler crawls image links from that page and downloads all the images. The page does not contain more than 100 image links at once. Even if the page is downloaded again after a given time interval, it will return the same image links. 

Can you briefly explain how would you achieve this setting time limitations? 
Thanks!

**Comment by sunshineatnoon** [comment]
@hardikvasa You can refer to [icrawler](https://github.com/hellock/icrawler)
