### ISSUE TITLE
about Reverse Image Search 

### ISSUE THREAD

**Issue by noorye4** [hardikvasa/google-images-download#43]
I follow the README command 

>python google-images-download.py -si "https://storage.googleapis.com/zopnow-static/images/products/320/fresh-apple-red-delicious-v-500-g.png" -l 10

I got some error : 
Traceback (most recent call last):
  File "google-images-download.py", line 393, in <module>
    errorCount = bulk_download(search_keyword,suffix_keywords,limit,main_directory,delay_time)
NameError: name 'search_keyword' is not defined

**Comment by hardikvasa** [comment]
thanks @noorye4 for reporting this...i will send send a fix soon!

**Comment by hardikvasa** [comment]
Issue resolved!
