### ISSUE TITLE
After finish downloading, it throws the following error all the time, which stales my script. Could you please share some suggestions? 

### ISSUE THREAD

**Issue by ados-h** [hardikvasa/google-images-download#44]
Traceback (most recent call last):
  File "/usr/bin/googleimagesdownload", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/google_images_download/__init__.py", line 2, in main
    import google_images_download.google_images_download
ImportError: No module named google_images_download

Thank you!

**Comment by rachmadaniHaryono** [comment]
Can you update your program till the latest commit?

**Comment by hardikvasa** [comment]
@ados-h this should be fixed in the new version of the package. If you are using pip, you can update the package using

`$ pip install google-images-download --upgrade`

Let me know if you still see this issue.
