### ISSUE TITLE
OSError directory name is invalid

### ISSUE THREAD

**Issue by alpha-256** [hardikvasa/google-images-download#45]
I installed by pip3 and while running an "SI" search it ouputs this:
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'TrainFiles\\2018-03-03 22:21:01'

**Comment by hardikvasa** [comment]
@alpha-256 Can you provide me your complete query and the OS version?

I am suspecting it is related to this:
https://stackoverflow.com/questions/45620324/oserror-winerror-123-the-filename-directory-name-or-volume-label-syntax-is?rq=1

**Comment by hardikvasa** [comment]
This was fixed in the latest update. Thanks for reporting it. Closing this issue now.
