### ISSUE TITLE
Use keyword file instead

### ISSUE THREAD

**Issue by BHWD** [hardikvasa/google-images-download#47]
Would it be possible to modify this so that we can use a txt or csv with a list of keywords? I have 400+ keywords to scrape images for and so manually doing it would take a while!

**Comment by hardikvasa** [comment]
@BHWD That would make a great feature. I will look into it.
Thanks!

**Comment by hardikvasa** [comment]
@BHWD this feature is implemented. You can now use `--keywords_from_file` or `-kf ` and specify the file name. One keyword/key phrase per line.

**Comment by BHWD** [comment]
That is brilliant thank you! Does it use the filename in the current directory?

**Comment by hardikvasa** [comment]
@BHWD yes, if the file is in the current directory, you can just specify just the filename in the path.

If the file is not in the current directory then you will have to specify the relative or the absolute path to the file.
