### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by ThomasKoscheck** [hardikvasa/google-images-download#5]
Hey, 
I am always having an IOError, can you help me out?

**Comment by hardikvasa** [comment]
Can you paste the complete error and the stack trace here? I would want to see where is the error getting generated from.

**Comment by ThomasKoscheck** [comment]
Thanks for your help, but I fixed my error. The script was in a folder without the permissions to write.

**Comment by hardikvasa** [comment]
Glad to know that!
