### ISSUE TITLE
More than one hyphen in keyword causes failure

### ISSUE THREAD

**Issue by stellpdc** [hardikvasa/google-images-download#52]
If a keyword has more than one hyphen, it will sometimes throw "Expecting property name enclosed in double quotes: line 1 column 2 (char 1)". It doesn't seem to do it with every example of this, but the ones that throw errors throw them every time. Log output attached.

[error2.txt](https://github.com/hardikvasa/google-images-download/files/1808521/error2.txt)

**Comment by hardikvasa** [comment]
@stellpdc Thanks for pointing this out. So this a bug that does not throw the correct error. The **actual issue** is that no images were found for this search query.

To test this, you can type `dorman 924-5226-8` on the [google images page](https://www.google.com/search?biw=1920&bih=916&tbm=isch&sa=1&ei=lEOoWozTDMaP0gLYtaGgBg&q=dorman+924-5226-8&oq=dorman+924-5226-8&gs_l=psy-ab.3...0.0.0.962349.0.0.0.0.0.0.0.0..0.0....0...1c..64.psy-ab..0.0.0....0.zxbJObc3K6g) and you would see no images are returned in the search.

I will fix the code to send correct feedback in the console (for e.g. "No Images Found").

**Comment by stellpdc** [comment]
Interesting. 

Additionally, it seems that this error also occurs when the number of images returned by the search is less than the program is expecting. Since the program defaults to downloading 100, if the search only returns 26 images, then the program throws this error.

**Comment by hardikvasa** [comment]
@stellpdc in cases where the images are less than the limit set in the query, you should see the following error:

`Unfortunately all 100 could not be downloaded because some images were not downloadable. 26 is all we got for this search filter!`

Can you give me an example query so I can reproduce this error on my end?

**Comment by stellpdc** [comment]
I've attached the keywords file and the command I'm using. 

I did a little more research. I've tried the following scenarios and gotten the following results for the keyword "Dorman 071-002":

1. Using the command and keyword file attached to this message, the program works at first, but then errors on the above keyword with the message "Expecting property name enclosed in double quotes: line 1 column 2 (char 1)". If I delete the offending keyword from the keyword file and run the program again, it will run successfully until it gets to another keyword that returns too few images and then crash.

2. Running `googleimagesdownload -p -e -l 25 -k "Dorman 071-002" -s large -o C:\Users\Stell\Desktop\dorman` causes no error and outputs the normal "Unfortunately, all 25 could not be downloaded..." message.

3. Running the command in the attachment with a keyword file containing only (3) keywords with "Dorman 071-002" being the middle one causes no error, outputs "Unfortunately, all 25 could not be downloaded...", and continues the program. 

As best I can tell, having too few image results only crashes the program when you have a keyword file with a huge number of keywords. 

[command.txt](https://github.com/hardikvasa/google-images-download/files/1811968/command.txt)
[keywords.txt](https://github.com/hardikvasa/google-images-download/files/1811969/keywords.txt)

**Comment by hardikvasa** [comment]
Thanks @stellpdc for the detailed description on the issue. Unfortunately I was not able to reproduce the issue that you are seeing. I have used your keyword file and the exact same query. At the time of writing I have reached keyword **202** and I do not see any errors yet.

The only thing I have changed was replace line 510 with this one:
`start_line = s.find('rg_meta notranslate')`

can you try that and see if that resolves the intermittent issue?

**Comment by hardikvasa** [comment]
@stellpdc can you confirm if the latest update resolved your issue?
