### ISSUE TITLE
allowing multiple values (Array) for file format argument

### ISSUE THREAD

**Issue by bijan-usf** [hardikvasa/google-images-download#57]
There are situations that we are interested in more than one specific file formats but not all formats. Currently the config file does not allow to have an array for "Format" attribute.

**Comment by hardikvasa** [comment]
@bijan-usf thanks for letting me know your use case.

as of now, google does not allow us to include more than one image formats in a single query. For now the workaround is to have more than one record in the config file like this:

```
{
    "Records": [
        {
            "keywords": "keyword1",
            "format": jpg
        },
        {
            "keywords": "keyword1",
            "format": png
        }
    ]
}
```

I can iterate through an array of formats in the code, but if i change it for format, then i will have to change it for all the other arguments as well. So i need to think of a better way of achieving this. Being said that, I have added this in my backlog of features. Closing the issue for now.
