### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by ak-01** [hardikvasa/google-images-download#6]
Hello!

Thank you for your great script. However sometimes requests are taking unlimited time. I wonder if it is possible to add a timeout to stop image requests.

req = Request( items[i], headers={"User-Agent": "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.27 Safari/537.17"})

**Comment by hardikvasa** [comment]
@ak-01 sorry for the delay in getting back on this. Thanks for reporting this issue. I have added a timeout of 15 seconds while downloading an image so it does not try infinitely. It would now throw an IOError if it cannot download an image in 15 seconds.

Thanks again.
