### ISSUE TITLE
 'related_images' and 'prefix_keywords' do not exit in args_list 

### ISSUE THREAD

**Issue by huchengsong** [hardikvasa/google-images-download#61]
'related_images' and 'prefix_keywords' do not exit in args_list in file google_images_download.py when installed by $ pip install google_images_download

**Comment by hardikvasa** [comment]
@huchengsong  thanks for reporting it. I am sending an update today which should fix this issue too!

**Comment by hardikvasa** [comment]
Have resolved this issue in the new release.

You can update it with `pip install google-images-download --upgrade`

Thanks.
