### ISSUE TITLE
Custom Resolution Option

### ISSUE THREAD

**Issue by CaseyKnauss** [hardikvasa/google-images-download#69]
There is an option for google image search size called "Exactly" where you can input a custom resolution like width = 3440  height = 1440 or '3440x1440'.  This would be really handy to get exact resolution images / aspect ratio control.  In the same vein a custom aspect ratio like "21:9" would be nice or a better explanation of panoramic vs wide.

**Comment by hardikvasa** [comment]
Great! thanks for the feature request.

The URL decoded version of your above example would convert to something like this
`isz:ex,iszw:3440,iszh:1440`

I will add the feature it in the next commit.

**Comment by hardikvasa** [comment]
This feature is added in the latest commit. You can specify the exact size using the `es` or `exact_size` argument.

Closing this issue.
