### ISSUE TITLE
ResourceWarning: unclosed file

### ISSUE THREAD

**Issue by adayton1** [hardikvasa/google-images-download#70]
I've had several downloaded images where the file is not closed properly and I get a ResourceWarning. I checked and in the download_image function there is no exception handling for opening and writing to the file. I don't even see the output file being closed.

`path = main_directory + "/" + dir_name + "/" + prefix + str(count) + ". " + image_name
  output_file = open(path, 'wb')
  data = response.read()
  output_file.write(data)
  response.close()`

The same issue is is the `single_image` function.

I'm less familiar with urlopen, but does it also need some exception handling so that the resource is closed if need be?

**Comment by adayton1** [comment]
`response` is a url object. `output_file` is a file descriptor. Both of them have to be closed, not just `response`.  There's not anything to the stack trace. I simply try to open a file, but I kept getting: ResourceWarning: unclosed file <_io.BufferedReader name='...'> for the files I downloaded.

**Comment by hardikvasa** [comment]
Thanks @adayton1 I will look into the PR #74 and merge it after testing.

**Comment by hardikvasa** [comment]
Closing this issue as #74 was merged.
