### ISSUE TITLE
Getting list of image names/file paths in response to the download method call

### ISSUE THREAD

**Issue by adayton1** [hardikvasa/google-images-download#71]
Maybe I just haven't seen how to do this yet, but when using this library in a Python script, it's not obvious how to get the information about the downloaded file from the `googleimagesdownload` object. It would be nice to have a dictionary of the relevant information about the downloaded image (i.e. basically the meta data that is printed out). At a minimum, it would be helpful to have the filenames of the downloaded images. The size would also be nice. Maybe this already exists, but I'm not sure how to get it.

**Comment by hardikvasa** [comment]
@adayton1 these features exist in the current version of the library. You can use `-p` for printing source URLs of the images, `-ps` to print the size of the images on disk, `-m` to print the metadata and `-e` t extract all of that in a text file.

It would however be good to return the metadata in the variable that is called after class instantiation. I will look into this. But yes these features already exist and details are in the documentation.

**Comment by adayton1** [comment]
Yes, I did see how to print them out. I just need to be able to access the downloaded files easily from inside the script, but there's no way to get the filepaths except to use `os.listdir`.

**Comment by YOnoda** [comment]
I'm on the same situation. The download method prints out all the information (via `extract_metadata`) but I would rather get the information as a variable as I need to change the filename.

**Comment by hardikvasa** [comment]
@adayton1 , @YOnoda the latest commit should have this feature...
the example in the documentation had been updated to reflect this change. You can now get list of absolute paths of all the images successfully downloaded in a variable.

closing this issue.
