### ISSUE TITLE
Images aren't actually saved to the output directory

### ISSUE THREAD

**Issue by adayton1** [hardikvasa/google-images-download#72]
I noticed that images weren't being directly downloaded to the output directory specified. A subdirectory is created in that output directory and the files are saved there. It's a hassle because I always have to move files up a directory. It would also be great to just name them 1.jpg, 2.jpg, etc... so that the file names are easy to sort by the order in which they are downloaded.

**Comment by luisverges** [comment]
Images are created in a subdirectory of the working directory, called "downloads" by default, and the name of which can be changed using the -o parameter. An easy workaround to your issue is executing the code one folder up from your desired output folder, and passing the parameter -o "desired output folder name"

**Comment by adayton1** [comment]
Images aren't created in `downloads`, though. If your keywords are "mountain river", then the files are saved in `downloads/mountain river`. I just want them to be saved in `downloads` directly.

**Comment by luisverges** [comment]
Excuse me, you are right. In any case, being able to choose the full path would  be ideal.

**Comment by adayton1** [comment]
Yes, being able to choose the full path for an image would be ideal. I think also this should be changed to a bug because if you have a search string that is too long, the folder creation will always break. Also, if there are commas in the search, that will break the folder creation.

**Comment by hardikvasa** [comment]
two new options added (--image-directory and --no_directory) that addresses this feature request. More information can be found in the docs.

Closing this issue for now.
