### ISSUE TITLE
Looks like we cannot locate the path the 'chromedriver' if limit is included

### ISSUE THREAD

**Issue by kevng9** [hardikvasa/google-images-download#73]
OS: osx 10.12.6
Python version: 3.6.5
Issue steps:
When running CLI with -l or --limit option specified, the following error is returned.
`Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine`
executing without -l works fine.

Attempted to use json input but still returning same error. json file contents below:
`{
    "Records": [
        {"keywords": "tops","limit": 1000},
        {"keywords": "jacket","limit": 1000}
    ]
}`

**Comment by hardikvasa** [comment]
@kevng9 the limit is set to 100 if you do not specify thee `-l` flag. If you want to download more than 100 images, you will have to specify the `-cd` flag and give the path to chromedriver that is installed in your machine. More details can be found in the documentation of this project.

Do let me know if that works for you.

**Comment by hardikvasa** [comment]
Closing this issue for now. If you are still experiencing this issue, feel free to reply back here.

**Comment by boxabirds** [comment]
@hardikvasa I'm having this error happen in this following environment:
Ubuntu 16.04.3 LTS
ChromeDriver 2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881) on port 9515

Command:
googleimagesdownload --config_file gid.json --chromedriver /home/<my user>/bin/chromedriver
... where that path does work I checked it separately.

**Comment by boxabirds** [comment]
The precise error is
(fastai) paperspace@ps2ev9u4q:~/data$ googleimagesdownload --config_file gid.json --chromedriver ../bin/chromedriver

Item no.: 1 --> Item name = vespa gtv
Evaluating...
Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine

**Comment by hardikvasa** [comment]
@boxabirds i am guessing based on your PR #98 , this issue is now resolved for you.

sorry for the late reply. Let me know if you have any other questions.

**Comment by boxabirds** [comment]
Hi no I'm not having any more luck, the exception doesn't take me any further. Nowhere can I find simple examples of where the chromedriver binary should be and the path that I included isn't working.

**Comment by kevinkit** [comment]
1. Have you tried giving the chromedriver inside python in a dictionary ? Maybe this will work and the error is somewhere in the argument parsing to it
2. is the path to the executable or to the folder containing the executable? It must be  directly to the executable, not only the folder
3. Why are there two "/" in your path? Maybe this breaks it
4. Try an absolute path

**Comment by hardikvasa** [comment]
@boxabirds yes it is either the path issue as Kevin suggested or it could be with the google chrome browser itself.

can you follow this guide to fresh install google-chrome-stable?
https://askubuntu.com/questions/510056/how-to-install-google-chrome

do let me know if that works.

**Comment by boxabirds** [comment]
Chrome's working fine -- I was able to run it directly ok. I'll have a look at it another time. BTW it'd be nice if you had an option to exclude the number prefixes. I've done a local build with a new flag that excludes it as an option

**Comment by Mozhdeh-d** [comment]
Hi,
I have the same issue. my chromedriver is installed in /usr/bin and I'm running the following code:
`python3 google_images_download.py -k 'cat' -cd ../../../usr/bin -l 140`

google_images_download.py file's path: ~/Documents/google-images-download/google_images_download

And the same error appears when I run the code: 
`Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine (exception: Message: 'bin' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
)
`

Any solution?

**Comment by omrysendik** [comment]
Exactly the same issue on my side...
I tried locating the chromedriver in the same folder of setup.py or in the same folder as google_images_download.py (changing the -cd path accordingly of course).
Nothing helped...

**Comment by omrysendik** [comment]
OK, I was able to make it work like this:

1. Installed the chromium-chromedriver: sudo apt-get install chromium-chromedriver
2. Adding the path to the selenium line.
    Line 167 in ./google_images_download/google_images_download.py to:
             browser = webdriver.Chrome("/usr/lib/chromium-browser/chromedriver")

**Comment by Mozhdeh-d** [comment]
@omrysendik thanks a lot for sharing your knowledge. It worked for me perfectly as well :+1:

**Comment by gjpicker** [comment]
chromdriver ==2.40 fail ,but re-roll to 2.37 ,all confused resolved   ,see  more detail in 
#120

**Comment by NathanYukai** [comment]
I was having the same problem, turns out you have to provide the path to the executable itself, not just the path. For example:   /usr/bin/chromedriver , not just   /usr/bin/

**Comment by Sushmitha-Gowda** [comment]
googleimagesdownload -k "car" -l 150 --chromedriver C:\Users\rsushmitha\Downloads\chromedriver_win323

Item no.: 1 --> Item name = car
Evaluating...
Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine (exception: Message: 'chromedriver_win323' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home)

**Comment by kranthik13** [comment]
I had my chromedriver in this location - "/usr/lib/chromium-browser/chromedriver"
So just append your previous command with --chromedriver /usr/lib/chromium-browser/chromedriver
 
Hope it helps.

**Comment by Kogam22** [comment]
> OK, I was able to make it work like this:
> 
>     1. Installed the chromium-chromedriver: sudo apt-get install chromium-chromedriver
> 
>     2. Adding the path to the selenium line.
>        Line 167 in ./google_images_download/google_images_download.py to:
>        browser = webdriver.Chrome("/usr/lib/chromium-browser/chromedriver")

Thank You ! This works perfectly fine.

**Comment by f2fish** [comment]
> OK, I was able to make it work like this:
> 
> 1. Installed the chromium-chromedriver: sudo apt-get install chromium-chromedriver
> 2. Adding the path to the selenium line.
>    Line 167 in ./google_images_download/google_images_download.py to:
>    browser = webdriver.Chrome("/usr/lib/chromium-browser/chromedriver")

 I find the easy to fix this
2.
googleimagesdownload -k "angelababy" -cd /usr/lib/chromium-browser/chromedriver -l 400

thanks everyone

**Comment by ASH1998** [comment]
While using arguments, 
you can specify the path...kinda like this

First
`response = google_images_download.googleimagesdownload() `
Then,
`arguments = {"keywords": query, 
				"format": "jpg", 
				"limit":200, 
				"print_urls":True, 
				"size": "medium", 
				"aspect_ratio": "panoramic",
				"output_directory": r"E:\Python Coding\Images download\Images3",
				"chromedriver": r"E:\DATA SETS & compressed\chromedriver_win32\chromedriver.exe"}`

Then,
`response.download(arguments)`

Keep it inside `try:` and `catch:`

**Comment by jqueguiner** [comment]
could also be you rights on the chromdriver are not the appropriate one (let's chromedriver is root root and you are trying to run the script as ubuntu ubuntu)

**Comment by talhaanwarch** [comment]
Here is the solution that work for me.
**Step 1**
Download chrome browser where you want it (https://chromedriver.chromium.org/downloads)

**Step 2**
`from google_images_download import google_images_download  `
press ctrl and click google_images_download and open google_images_download.py file
go to line 177 where it is written as `browser = webdriver.Chrome(chromedriver, chrome_options=options)`

change it to `browser = webdriver.Chrome("D:/chromedriver_win32/chromedriver", chrome_options=options)`

Here chromedriver is not the name of folder, but its the exe file

Note: This (D:/chromedriver_win32/) should be your path to chrome file

**Comment by jiaqiwang1212** [comment]
> Here is the solution that work for me.
> **Step 1**
> Download chrome browser where you want it (https://chromedriver.chromium.org/downloads)
> 
> **Step 2**
> `from google_images_download import google_images_download `
> press ctrl and click google_images_download and open google_images_download.py file
> go to line 177 where it is written as `browser = webdriver.Chrome(chromedriver, chrome_options=options)`
> 
> change it to `browser = webdriver.Chrome("D:/chromedriver_win32/chromedriver", chrome_options=options)`
> 
> Here chromedriver is not the name of folder, but its the exe file
> 
> Note: This (D:/chromedriver_win32/) should be your path to chrome file


I use the same method as you, but I still get wrong.
 File "google_images_download.py", line 179
    browser = webdriver.Chrome(‪'D:/chromedriver_win32/chromedriver', chrome_options=options)
                                                                                             ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by talhaanwarch** [comment]
> > Here is the solution that work for me.
> > **Step 1**
> > Download chrome browser where you want it (https://chromedriver.chromium.org/downloads)
> > **Step 2**
> > `from google_images_download import google_images_download `
> > press ctrl and click google_images_download and open google_images_download.py file
> > go to line 177 where it is written as `browser = webdriver.Chrome(chromedriver, chrome_options=options)`
> > change it to `browser = webdriver.Chrome("D:/chromedriver_win32/chromedriver", chrome_options=options)`
> > Here chromedriver is not the name of folder, but its the exe file
> > Note: This (D:/chromedriver_win32/) should be your path to chrome file
> 
> I use the same method as you, but I still get wrong.
> File "google_images_download.py", line 179
> browser = webdriver.Chrome(‪'D:/chromedriver_win32/chromedriver', chrome_options=options)
> ^
> TabError: inconsistent use of tabs and spaces in indentation

actually you have made indentation error. can you post the screen shot

**Comment by 521168queen** [comment]
> > > 这是适合我的解决方案。
> > > **步骤1** 
> > > 在您想要的地方下载Chrome浏览器（https://chromedriver.chromium.org/downloads）
> > > **步骤2**
> > > `from google_images_download import google_images_download ` 
> > > 按ctrl并单击google_images_download并打开google_images_download.py文件
> > > 转到第177行，将其写为`browser = webdriver.Chrome(chromedriver, chrome_options=options)`
> > > 将其更改为`browser = webdriver.Chrome("D:/chromedriver_win32/chromedriver", chrome_options=options)`
> > > 此处chromedriver是不是文件夹的名称，而是它的exe文件
> > > 注意：这个（D：/ chromedriver_win32 /）应该是你的chrome文件的路径
> > 
> > 
> > 我使用与你相同的方法，但我仍然错了。
> > 文件“google_images_download.py”，第179行
> > browser = webdriver.Chrome（'D：/ chromedriver_win32 / chromedriver'，chrome_options = options）
> > ^ 
> > TabError：缩进中标签和空格的使用不一致
> 
> 实际上你做了缩进错误。你可以张贴屏幕截图吗？
![QQ截图20190915215203](https://user-images.githubusercontent.com/40316182/64922559-1f1ce680-d803-11e9-8e4c-87769bf70fe5.jpg)

**Comment by 521168queen** [comment]
> > > > 这是适合我的解决方案。
> > > > **步骤1** 
> > > > 在您想要的地方下载铬浏览器（[https://chromedriver.chromium.org/downloads）](https://chromedriver.chromium.org/downloads%EF%BC%89)
> > > > **步骤2**
> > > > `from google_images_download import google_images_download ` 
> > > > 按CTRL并单击google_images_download打开并google_images_download.py文件
> > > > 转到第177行，将其写为`browser = webdriver.Chrome(chromedriver, chrome_options=options)`
> > > > 将其更改为`browser = webdriver.Chrome("D:/chromedriver_win32/chromedriver", chrome_options=options)`
> > > > 此处chromedriver是不是文件夹的名称，而是它的exe文件
> > > > 注意：这个（D：/ chromedriver_win32 /）应该是你的chrome文件的路径
> > > 
> > > 
> > > 我使用与你相同的方法，但我仍然错了。
> > > 文件“google_images_download.py”，第179行
> > > browser = webdriver.Chrome（'D：/ chromedriver_win32 / chromedriver'，chrome_options = options）
> > > ^ 
> > > TabError：缩进中标签和空格的使用不一致
> > 
> > 
> > 实际上你做了缩进错误。你可以张贴屏幕截图吗？
> > ![QQ截图20190915215203](https://user-images.githubusercontent.com/40316182/64922559-1f1ce680-d803-11e9-8e4c-87769bf70fe5.jpg)

![QQ截图20190915215436](https://user-images.githubusercontent.com/40316182/64922588-728f3480-d803-11e9-9eaa-806348a77c41.jpg)

**Comment by jiaqiwang1212** [comment]
sorry，

> > > Here is the solution that work for me.
> > > **Step 1**
> > > Download chrome browser where you want it (https://chromedriver.chromium.org/downloads)
> > > **Step 2**
> > > `from google_images_download import google_images_download `
> > > press ctrl and click google_images_download and open google_images_download.py file
> > > go to line 177 where it is written as `browser = webdriver.Chrome(chromedriver, chrome_options=options)`
> > > change it to `browser = webdriver.Chrome("D:/chromedriver_win32/chromedriver", chrome_options=options)`
> > > Here chromedriver is not the name of folder, but its the exe file
> > > Note: This (D:/chromedriver_win32/) should be your path to chrome file
> > 
> > 
> > I use the same method as you, but I still get wrong.
> > File "google_images_download.py", line 179
> > browser = webdriver.Chrome(‪'D:/chromedriver_win32/chromedriver', chrome_options=options)
> > ^
> > TabError: inconsistent use of tabs and spaces in indentation
> 
> actually you have made indentation error. can you post the screen shot

![image](https://user-images.githubusercontent.com/40316182/64922677-78d1e080-d804-11e9-9a97-9d2746ba19c7.png)

**Comment by 521168queen** [comment]
![image](https://user-images.githubusercontent.com/40316182/64922731-1a593200-d805-11e9-8c75-eb20eae8a9a6.png)

**Comment by jiaqiwang1212** [comment]
> sorry，
> 
> > > > Here is the solution that work for me.
> > > > **Step 1**
> > > > Download chrome browser where you want it (https://chromedriver.chromium.org/downloads)
> > > > **Step 2**
> > > > `from google_images_download import google_images_download `
> > > > press ctrl and click google_images_download and open google_images_download.py file
> > > > go to line 177 where it is written as `browser = webdriver.Chrome(chromedriver, chrome_options=options)`
> > > > change it to `browser = webdriver.Chrome("D:/chromedriver_win32/chromedriver", chrome_options=options)`
> > > > Here chromedriver is not the name of folder, but its the exe file
> > > > Note: This (D:/chromedriver_win32/) should be your path to chrome file
> > > 
> > > 
> > > I use the same method as you, but I still get wrong.
> > > File "google_images_download.py", line 179
> > > browser = webdriver.Chrome(‪'D:/chromedriver_win32/chromedriver', chrome_options=options)
> > > ^
> > > TabError: inconsistent use of tabs and spaces in indentation
> > 
> > 
> > actually you have made indentation error. can you post the screen shot
> 
> ![image](https://user-images.githubusercontent.com/40316182/64922677-78d1e080-d804-11e9-9a97-9d2746ba19c7.png)

![image](https://user-images.githubusercontent.com/40316182/64922740-2e049880-d805-11e9-81e1-28720c45a0d8.png)

**Comment by talhaanwarch** [comment]
> > sorry，
> > > > > Here is the solution that work for me.
> > > > > **Step 1**
> > > > > Download chrome browser where you want it (https://chromedriver.chromium.org/downloads)
> > > > > **Step 2**
> > > > > `from google_images_download import google_images_download `
> > > > > press ctrl and click google_images_download and open google_images_download.py file
> > > > > go to line 177 where it is written as `browser = webdriver.Chrome(chromedriver, chrome_options=options)`
> > > > > change it to `browser = webdriver.Chrome("D:/chromedriver_win32/chromedriver", chrome_options=options)`
> > > > > Here chromedriver is not the name of folder, but its the exe file
> > > > > Note: This (D:/chromedriver_win32/) should be your path to chrome file
> > > > 
> > > > 
> > > > I use the same method as you, but I still get wrong.
> > > > File "google_images_download.py", line 179
> > > > browser = webdriver.Chrome(‪'D:/chromedriver_win32/chromedriver', chrome_options=options)
> > > > ^
> > > > TabError: inconsistent use of tabs and spaces in indentation
> > > 
> > > 
> > > actually you have made indentation error. can you post the screen shot
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/40316182/64922677-78d1e080-d804-11e9-9a97-9d2746ba19c7.png)
> 
> ![image](https://user-images.githubusercontent.com/40316182/64922740-2e049880-d805-11e9-81e1-28720c45a0d8.png)

apparently it seems you have some issue with indentations, can you undo all changes, you have made.
you can try pip uninstall google_images_download
and then install again.
make sure, instead of changing the complete 
`browser = webdriver.Chrome(chromedriver, chrome_options=options)`
just change `chromedriver`.
 this will help to avoid indentation issue

**Comment by rozeappletree** [comment]
> > > sorry，
> > > > > > Here is the solution that work for me.
> > > > > > **Step 1**
> > > > > > Download chrome browser where you want it (https://chromedriver.chromium.org/downloads)
> > > > > > **Step 2**
> > > > > > `from google_images_download import google_images_download `
> > > > > > press ctrl and click google_images_download and open google_images_download.py file
> > > > > > go to line 177 where it is written as `browser = webdriver.Chrome(chromedriver, chrome_options=options)`
> > > > > > change it to `browser = webdriver.Chrome("D:/chromedriver_win32/chromedriver", chrome_options=options)`
> > > > > > Here chromedriver is not the name of folder, but its the exe file
> > > > > > Note: This (D:/chromedriver_win32/) should be your path to chrome file
> > > > > 
> > > > > 
> > > > > I use the same method as you, but I still get wrong.
> > > > > File "google_images_download.py", line 179
> > > > > browser = webdriver.Chrome(‪'D:/chromedriver_win32/chromedriver', chrome_options=options)
> > > > > ^
> > > > > TabError: inconsistent use of tabs and spaces in indentation
> > > > 
> > > > 
> > > > actually you have made indentation error. can you post the screen shot
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/40316182/64922677-78d1e080-d804-11e9-9a97-9d2746ba19c7.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/40316182/64922740-2e049880-d805-11e9-81e1-28720c45a0d8.png)
> 
> apparently it seems you have some issue with indentations, can you undo all changes, you have made.
> you can try pip uninstall google_images_download
> and then install again.
> make sure, instead of changing the complete
> `browser = webdriver.Chrome(chromedriver, chrome_options=options)`
> just change `chromedriver`.
> this will help to avoid indentation issue

Thankyou @talhaanwarch It works as charm !

**Comment by svyotov** [comment]
I had this issue too, the issue is that all command line arguments are ignored when the config file argument is present. `googleimagesdownload  -cf cfg.json --chromedriver '/usr/bin/chromedriver'` will ignore the `--chromedriver` argument. You can add it to the configuration file `{ "Records": [ {"keywords": "tops","limit": 1000, "chromedriver": "/usr/bin/chromedriver"}, {"keywords": "jacket","limit": 1000, "chromedriver": "/usr/bin/chromedriver"} ] }`, a bit too verbose, but it works.

**Comment by nicejava** [comment]
Use chormedriver 80 so will solved this problem 
https://chromedriver.storage.googleapis.com/index.html?path=80.0.3987.106/

eg. When i extract chormedriver exe to chromedriver_win32-80
    
    chromedriver = "chromedriver_win32-80/chromedriver.exe"
    response = google_images_download.googleimagesdownload()
    response.download({
        "keywords": "portrait transparent background",
        "color_type": "transparent",
        "size": "medium",
        "limit": 500,
        "output_directory": output_dir,
        "chromedriver": chromedriver})

**Comment by ss32** [comment]
> Use chormedriver 80 so will solved this problem
> https://chromedriver.storage.googleapis.com/index.html?path=80.0.3987.106/
> 
> eg. When i extract chormedriver exe to chromedriver_win32-80
> 
> ```
> chromedriver = "chromedriver_win32-80/chromedriver.exe"
> response = google_images_download.googleimagesdownload()
> response.download({
>     "keywords": "portrait transparent background",
>     "color_type": "transparent",
>     "size": "medium",
>     "limit": 500,
>     "output_directory": output_dir,
>     "chromedriver": chromedriver})
> ```

Failing, but in a new way for me

```
$ googleimagesdownload -l=5000 -k "car" --chromedriver  $(pwd)/chromedriver

Item no.: 1 --> Item name = car
Evaluating...
Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine (exception: Message: session not created: This version of ChromeDriver only supports Chrome version 80
)
```

**Comment by ss32** [comment]
> > Use chormedriver 80 so will solved this problem
> > https://chromedriver.storage.googleapis.com/index.html?path=80.0.3987.106/
> > eg. When i extract chormedriver exe to chromedriver_win32-80
> > ```
> > chromedriver = "chromedriver_win32-80/chromedriver.exe"
> > response = google_images_download.googleimagesdownload()
> > response.download({
> >     "keywords": "portrait transparent background",
> >     "color_type": "transparent",
> >     "size": "medium",
> >     "limit": 500,
> >     "output_directory": output_dir,
> >     "chromedriver": chromedriver})
> > ```
> 
> Failing, but in a new way for me
> 
> ```
> $ googleimagesdownload -l=5000 -k "car" --chromedriver  $(pwd)/chromedriver
> 
> Item no.: 1 --> Item name = car
> Evaluating...
> Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine (exception: Message: session not created: This version of ChromeDriver only supports Chrome version 80
> )
> ```

Solved by matching the version of `chromedriver` with my version of Chromium

```
googleimagesdownload -l 5000 -k "car" -cd $(pwd)/chromedriver

Item no.: 1 --> Item name = car
Evaluating...
Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine (exception: Message: session not created: This version of ChromeDriver only supports Chrome version 89
Current browser version is 87.0.4280.66 with binary path /usr/bin/chromium-browser
)
```

After downloading the correct version

```
$ googleimagesdownload -l 5000 -k "car" -cd $(pwd)/chromedriver

Item no.: 1 --> Item name = car
Evaluating...
Getting you a lot of images. This may take a few moments...
```
