### ISSUE TITLE
Limit isn't working

### ISSUE THREAD

**Issue by MuhammedBuyukkinaci** [hardikvasa/google-images-download#79]
Hi,
I am trying to download images. I determined limit as 10000. However, downloading stopped near 600th image. I used a config file as below:
![screenshot 12](https://user-images.githubusercontent.com/33747602/38782238-41837308-40f9-11e8-9b23-2f70499082f4.png)
But, the result on command line is below:
Unfortunately all 10000 could not be downloaded because some images were not downloadable. 646 is all we got for this search filter!
![screenshot 13](https://user-images.githubusercontent.com/33747602/38782253-689ba168-40f9-11e8-8c5c-f8d1649a426c.png)

**Comment by luisverges** [comment]
Same here. I'd try to help with the issue, but I am not super-fluent. 

This is my output: 
> Unfortunately all 5000 could not be downloaded because some images were not downloadable. 690 is all we got for this search filter!


This is how I called the program: 
`googleimagesdownload -k "{class1}" -l 5000 -f "jpg" -o "{namefolder}" -cd "C:\\Users\\{username}\\google-images-download\\chromedriver.exe"`

**Comment by hardikvasa** [comment]
@MuhammedBuyukkinaci sry for the late response, as @luisverges mentioned, and that is correct...this script gets all the images that google image search result returns. So if the image search returns only 600 images, it will only download 600 of em.

Closing this issue.
