### ISSUE TITLE
Limit over 100 won't work

### ISSUE THREAD

**Issue by kevinkit** [hardikvasa/google-images-download#80]
Great API, however when using something like:

```
arguments =         {
            "keywords": "red",
            "limit": imgs,
            "color": "red",
            "print_urls": True,
            "format" : "jpg"
        }


response.download(arguments)  

```

and setting `imgs ` over 100,like 120 

I am getting the following error: 

_Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine
An exception has occurred, use %tb to see the full traceback._

Using Python 3.6 with Spyder

**Comment by axzxc1236** [comment]
You mean "limits" augment.
Install Google Chrome and download [Chromedriver](https://sites.google.com/a/chromium.org/chromedriver/downloads).
And add a augment
"chromedriver":"C:\\blahblahblah\\chromedriver.exe"

**Comment by kevinkit** [comment]
Thank you for that hint, but why does it work when it is under 100 ?

**Comment by axzxc1236** [comment]
I don't know, I am just a guy that runs into the same problem 30 minutes ago, but this behavior is specified in README.

**Comment by kevinkit** [comment]
Duh, thank you - I totally overread that

**Comment by vk1z** [comment]
Well, at least for me on linux, adding the chromedriver arg worked just fine
