### ISSUE TITLE
Improve the description of "limits" augment.

### ISSUE THREAD

**Issue by axzxc1236** [hardikvasa/google-images-download#82]
Turns out "limits" augment doesn't mean it will download **exactly** "limits" amount of pictures. (because errors happened.)

It would also be nice if you add an augments that make counter ignores errors.
(For example I failed to download 10th picture, instead of counting the next picture as 11th, make it count as 10th picture.)

**Comment by hardikvasa** [comment]
Thanks! I have added a note in the documentation within the `limit` argument for transparancy. This is only the case where the limit is set to **100** and there are errors.

If you set a limit to less than 100 or more than 100, it will get you the exact number of images (even if there are errors).

Closing this for now.
