### ISSUE TITLE
httplib.HTTPException: got more than 100 headers

### ISSUE THREAD

**Issue by jaredjohansen** [hardikvasa/google-images-download#85]
When I run this command:

> python google-images-download/google_images_download/google_images_download.py --keywords "blood moon" --print_urls --limit 300 --chromedriver ./chromedriver --o blood-moon --format jpg

I eventually get the following error (around image 141):

> Completed Image ====> 141. b5ba5723-c77a-45af-b1d9-fc7035eed1b1-getty-490376722.jpg
> Image URL: http://www.latimes.com/resizer/98_OZySBlPPTMdmxqUBRwqMVi-o=/1400x0/arc-anglerfish-arc2-prod-tronc.s3.amazonaws.com/public/X3ES6TPM5FDVBEOZ4UFQCKX2QE.jpg
> Traceback (most recent call last):
>   File "google-images-download/google_images_download/google_images_download.py", line 792, in <module>
>     main()
>   File "google-images-download/google_images_download/google_images_download.py", line 784, in main
>     response.download(arguments)
>   File "google-images-download/google_images_download/google_images_download.py", line 742, in download
>     items,errorCount = self._get_all_items(raw_html,main_directory,dir_name,limit,arguments)    #get all image items and download images
>   File "google-images-download/google_images_download/google_images_download.py", line 631, in _get_all_items
>     download_status,download_message,return_image_name = self.download_image(object['image_link'],object['image_format'],main_directory,dir_name,count,arguments['print_urls'],arguments['socket_timeout'],arguments['prefix'],arguments['print_size'])
>   File "google-images-download/google_images_download/google_images_download.py", line 518, in download_image
>     response = urlopen(req, None, timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 429, in open
>     response = self._open(req, data)
>   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
>     '_open', req)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
>     return self.do_open(httplib.HTTPConnection, req)
>   File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
>     r = h.getresponse(buffering=True)
>   File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
>     response.begin()
>   File "/usr/lib/python2.7/httplib.py", line 485, in begin
>     self.msg = HTTPMessage(self.fp, 0)
>   File "/usr/lib/python2.7/mimetools.py", line 25, in __init__
>     rfc822.Message.__init__(self, fp, seekable)
>   File "/usr/lib/python2.7/rfc822.py", line 108, in __init__
>     self.readheaders()
>   File "/usr/lib/python2.7/httplib.py", line 312, in readheaders
>     raise HTTPException("got more than %d headers" % _MAXHEADERS)
> httplib.HTTPException: got more than 100 headers

Any suggestions?

**Comment by hardikvasa** [comment]
@jaredjohansen Not sure whats causing this exception. I will test this out later today and revert back. Can you tell me if you are:

* on OSX or Linux?
* does this happen on all the queries? or is this just intermittent?

**Comment by jaredjohansen** [comment]
I am using Linux (Ubuntu 16.04).

This happens intermittently.  Of the ~100 queries I've used, it only happened twice.  The first one went away the second time I used it.  The example provided above was repeatable.  I believe it occurred 3x.

No, I am not (knowingly) setting _MAXHEADERS anywhere in my environment.

**Comment by hardikvasa** [comment]
@jaredjohansen sry for the delay. I have made some improvements in the lib so you should not see this error. I am not closing both the request as well as the file descriptor.

But if you do see this error after installing the latest version of this lib, do let me know.

closing this for now.

**Comment by jaredjohansen** [comment]
Hardik,
Haven’t seen anything.  If it pops up again, I’ll let you know.

Thanks for your great support!
Jared
