### ISSUE TITLE
Unicode keyword cause problem when printing to console on Windows

### ISSUE THREAD

**Issue by krissdap** [hardikvasa/google-images-download#89]
Hi Hardik and guys,

Thanks for this great tool.

I'd like to report an issue, when using non-English search word, it causes the program to throw an error and quit.

I'm not sure if this is specific to some platform or locale.
Mine is Windows 10 64-bit English version.

I tried to use some Thai words and the error occurs on the <code>print(iteration)</code> line.
Obviously this is just a status message which the program would work just fine if the line is commented out.

I learned that we're only supposed to use characters in the <code>string.printable</code> when outputting to console. So my solution is to replace the line with 
<code>print(iteration.encode(encoding='utf-8', errors='replace'))</code>, which will replace non-printable characters with their Unicode escape sequence e.g. "\xe0\xb8\xad\" which works fine for me.

But I'm not sure which is the best way to fix or which is your preferred way.
So let me know if I can help.

Thanks.

**Comment by hardikvasa** [comment]
Thanks @krissdap for reporting this issue. Can you give me an example keyword/query that you used when you saw this issue on the console? Once i can reproduce this issue, I will have better understanding of how to fix this.

**Comment by krissdap** [comment]
Hi @hardikvasa ,
May be you can try one of the following:
สวัสดีครับ
อร่อย
ขอบคุณครับ
(it means, hello, delicious, and thank you :)

Just some more info about error, the error message is:
<code>
  File "C:\Python35\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 30-39: character maps to \<undefined\>
</code>

Thanks :)

**Comment by MHM5000** [comment]
Any updates on this issue? Especially for `python 2.7`.

**Comment by krissdap** [comment]
Hi @MHM5000 

I guess the issue is not universal (may be not reproducible in MacOS -- just guess).
So I think the original author have not decided.

Anyway, for workaround, you could just comment out that specific line, that print out the search keyword.
Works for me.

**Comment by enricopal** [comment]
I've also stumbled upon this issue with python 3.6.3. Works fine with 3.6.0.

**Comment by krissdap** [comment]
Just a little update.
I just tested on Ubuntu desktop and all is fine. (Gnome's terminal supports UTF-8 output)
So I guess the issue is specific to Windows at this point.

**Comment by GoTop** [comment]
when I useing the Chinese as keyword，and set the argument “metadata”，this error occure
```
print("\nImage Metadata: " + str(object))
UnicodeEncodeError: 'gbk' codec can't encode character '\xe7' in position 212: illegal multibyte sequence
```

Then I change some the code in function format_object(self, object)
`formatted_object['image_description'] = object['pt']`
to
`formatted_object['image_description'] = object['pt'].encode('raw_unicode_escape').decode('utf-8')`

then it‘s OK to set the argument “metadata” to prints the metada of the image on the console.

**Comment by krissdap** [comment]
I can confirm that appending 
<code>
.encode('raw_unicode_escape').decode('utf-8')
</code>
to the string being printed to screen solved my original issue.

Thanks GoTop!

**Comment by GoTop** [comment]
> I can confirm that appending
> ` .encode('raw_unicode_escape').decode('utf-8') `
> to the string being printed to screen solved my original issue.
> 
> It will escape unprintable text to `\u0000` style string, and printable text stay the same.
> 
> Thanks GoTop!

I notice some `\u0000` style strings are printed on the screnn too, do you know how to translate them into normal string?

**Comment by GoTop** [comment]
A little update to solve the problem:
some unprintable character show as unicode like "\\u201c" in the json file which save images' metadata.

In function format_object(self, object)
change the code:
`formatted_object['image_description'] = object['pt']`
to
```
description = object['pt'].encode('raw_unicode_escape').decode('utf-8')
description = description.encode('unicode-escape').replace(b'\\\\', b'\\').decode('unicode-escape')
formatted_object['image_description'] = description
```

**Comment by hardikvasa** [comment]
@krissdap Sorry for the delay in getting to this. Working on resolving this now. I will test it in one of the windows instances but can you confirm if changing the below lines would suffice for both **python2 and python 3**?

* `print(iteration)` to `print(iteration.encode('raw_unicode_escape').decode('utf-8'))`
* `print(paths)` to `print(paths.encode('raw_unicode_escape').decode('utf-8'))`
* `print("completed ====> " + image_name)` to `print("completed ====> " + image_name.encode('raw_unicode_escape').decode('utf-8'))`

this will prevent from throwing errors for terminals that do not support encodings.

**Comment by hardikvasa** [comment]
Made the above changes to the print statements. Do let me know if this is still an issue.

**Comment by krissdap** [comment]
Hi @hardikvasa 

So I have just tested your solution on Python 2.7.15 (64-bit) and Python 3.6.8 (64-bit) on Windows 10 64-bit, and it works fine. (Unprintable chars are displayed with \u0e02, etc).

Thanks.

P.S. Noticed that you have the <code>print(iteration)</code> and <code>print("completed ====> " + image_name</code> fixes in place. But still not yet the fix for <code>print(paths)</code>.

Best Regards.

**Comment by Aidenir** [comment]
Not sure I understand what the problem is in this thread, just wanted to give a heads up that code I ran a few weeks back no longer works:
```
(venv) ~/git/some-project❯ python3 parser.py                  
Traceback (most recent call last):
  File "parser.py", line 67, in <module>
    main()
  File "parser.py", line 62, in main
    dl_image(line)
  File "parser.py", line 39, in dl_image
    paths = response.download(arguments)   #passing the arguments to the function
  File "/home/viktor/.local/lib/python3.5/site-packages/google_images_download/google_images_download.py", line 851, in download
    print(iteration.encode('raw_unicode_escape').decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 34: invalid continuation byte
```
The code that produces this is:
```python
    response = google_images_download.googleimagesdownload()   #class instantiation
    arguments = {'print_urls': True, 'no_directory': True, 'size': 'large', 'no_numbering': True, 'keywords': 'Blomkål- och potatissoppaTomatsoppa', 'limit': 1}#creating list of arguments
    paths = response.download(arguments)   #passing the arguments to the function
```
Downgrading to 2.5.0 this works perfectly.

**Comment by SerialForBreakfast** [comment]
I'm getting this same error when attempting to read a keyword with unicode from a config.json file.  Tested on mac and ubuntu.
`search_keyword = [str(item) for item in arguments['keywords'].split(',')]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 1: ordinal not in range(128)`
