### ISSUE TITLE
Unable to download more than 100 images in windows

### ISSUE THREAD

**Issue by shravik** [hardikvasa/google-images-download#91]
Hi,

As mentioned in the documents, I am calling your library through another file in python. I have also set the path to chrome driver in the arguments but still I am unable to download more than 100 images. I am however able to download up to 100 images. How do I fix this situation as I need more than 100 image downloads ?

Thanks for sharing this awesome tool and thank you for reading.

**Comment by kevinkit** [comment]
When you say "unable" does it mean that it chrashes with an error message or that it just won't be 100 images?

**Comment by shravik** [comment]
Yes, I get an error message like this: 

Item no.: 1 --> Item name = Buildings
Evaluating...
Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine

**Comment by kevinkit** [comment]
Can you show us how you specified the chromedriver? 


It has to be an absolute path and it should be to the .exe , means:


`C:\\Users\\user\\mypath\\chromedriver.exe`

**Comment by shravik** [comment]
this is the way I mentioned in my arguments:

"chromedriver":"C:\Users\sravanthi.kanchi\Documents\chromedriver.exe"

**Comment by shravik** [comment]
I have also tried using the chromedriver argument this way:

"chromedriver":"C://Users/sravanthi.kanchi/Documents/chromedriver.exe"

**Comment by shravik** [comment]
@kevinkit  Thanks a lot ! its working now

**Comment by hardikvasa** [comment]
@kevinkit for your help. I have now added some clarification on providing chromedriver path in on Windows OS.

**Comment by Sushmitha-Gowda** [comment]
same error

googleimagesdownload -k "car" -l 150 --chromedriver C:\\Users\\rsushmitha\\Downloads\\chromedriver_win323\\chromedriver.exe

Item no.: 1 --> Item name = car
Evaluating...
Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine (exception: Message: 'chromedriver_win323' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
)

**Comment by hardikvasa** [comment]
@Sushmitha-Gowda can you refer to the above answers and mention the path of the chromedriver accordingly? Do let me know if that works for you.

**Comment by Sushmitha-Gowda** [comment]
Ya that is working fine, but now
1. some as images are shown just as dot
2. while using similar images argument.. i m getting following errors as
shown in screenshots.

Anyways great code,thank you so much
