### ISSUE TITLE
Bug - The time_range filter is ignored and the same images are returned

### ISSUE THREAD

**Issue by danavrahami** [hardikvasa/google-images-download#93]
Hi,
In the python implementation - 
file **google_images_download.py, line 353.**
In the function **build_url_parameters**, for the switch on **time_range**:

`if arguments['time_range']:`

The value of time_range has a redundant ampersand (&) before "cdr" - **&cdr**

`time_range = '&cdr:1,cd_min:' + d['time_min'] + ',cd_max:' + d['time_min']`

It should be **cdr**

`time_range = 'cdr:1,cd_min:' + d['time_min'] + ',cd_max:' + d['time_min']`

Without fixing it, google will ignore the filtering by time_range.

**Code example for reproducing the error:**
Both cases return **the same images** although we specify **different time_min and time_max** (it simply ignores the time_range filter):

**Case 1 - 'time_range': str({"time_min":"04/05/2017","time_max":"04/06/2017"}),**
```
response = google_images_download.googleimagesdownload()
arguments = {"keywords": "dog",
             "limit": 3,
             "print_urls": True,
             'time_range': str({"time_min":"04/05/2017","time_max":"04/06/2017"}),
             "output_directory" : '/home/dan/google_images_download/downloads/'}
response.download(arguments)  # passing the arguments to the function
```

**Case 2 - 'time_range': str({"time_min":"04/08/2017","time_max":"04/09/2017"}),**
```
response = google_images_download.googleimagesdownload()
arguments = {"keywords": "dog",
             "limit": 3,
             "print_urls": True,
             'time_range': str({"time_min":"04/08/2017","time_max":"04/09/2017"}),
             "output_directory" : '/home/dan/google_images_download/downloads/'}
response.download(arguments)  # passing the arguments to the function
```

Thanks,
Dan.

**Comment by hardikvasa** [comment]
@danavrahami thanks for the detailed explanation on this issue.

I have now corrected this error in the code update. Do let me know if you have any other questions.

Closing this issue.
