### ISSUE TITLE
Chromedriver Error Mac 

### ISSUE THREAD

**Issue by gottlism** [hardikvasa/google-images-download#96]
I am getting the error "Looks like we cannot locate the path the 'chromedriver' (use the '--chromedriver' argument to specify the path to the executable.) or google chrome browser is not installed on your machine"

I have chromedriver located in my projectDirectory and my arguments appears below. 
`arguments = {"chromedriver": "/Users/Documents/google-images-download", "keywords": "Polar bears", "limit": 1000, "print_urls": False}  # creating list of arguments`

Any help would be appreciated. Thank you!

**Comment by kevinkit** [comment]
The path to chromedriver needs to be to the .exe, so Just add
//chromedriver.exe to it

gottlism <notifications@github.com> schrieb am Di., 8. Mai 2018, 18:09:

**Comment by gottlism** [comment]
Thanks for the quick reply. 
I tried `arguments = {"keywords": "Polar bears", "limit": 1000, "print_urls": False, "chromedriver": "/Users/Documents/google-images-download/chromedriver.exe"}` along with just "chromedriver.exe" and still get the same error. 

Should it all be single slashes?

**Comment by kevinkit** [comment]
It musr bei C:\\Users ...

So:

1. Put the C:\\ in front
2. Replace all / with \\

gottlism <notifications@github.com> schrieb am Di., 8. Mai 2018, 18:26:

**Comment by gottlism** [comment]
I tried it with the same error. I'm on a Mac so I don't think C:\\ will work

**Comment by kevinkit** [comment]
Ah Sry thouht it would be a Windows machine. Nevertheless it has to be an
absolute path

gottlism <notifications@github.com> schrieb am Di., 8. Mai 2018, 18:33:

**Comment by gottlism** [comment]
Got it, thanks for your help! I ended up using 
`/Users/Documents/google-images-download/chromedriver`

Which I thought was the first option I tried but alas. 

Great piece of software you have here. Thanks for sharing it.

**Comment by hardikvasa** [comment]
@kevinkit Thanks for your assistance on the issue. :)
