### ISSUE TITLE
I can't download more than 100 images

### ISSUE THREAD

**Issue by nauti16** [hardikvasa/google-images-download#97]
Dear creaters, 

Thanks for this great tool.
I tried download 1000 images with this tool from google but I can't with below response.
I installed chromedriver and selenium along with instructions.

Item no.: 1 --> Item name = balloon
Evaluating...
[0509/201011.041:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:12501/devtools/browser/f0c8f836-50cb-4369-8707-2cf5741a7bc4

KLIB_SelfTest return : KLR_OK
Getting you a lot of images. This may take a few moments...
Reached end of Page.
Starting Download...
Completed Image ====> 1. 41acepl7dml._sl500_ac_ss350_.jpg
...(trying downloads images)...
Completed Image ====> 89. isolated-shot-of-red-balloon-with-ribbon-against-white-background-picture-id172354758.jpg

Unfortunately all 1000 could not be downloaded because some images were not down
loadable. 89 is all we got for this search filter!

Errors: 2

When I try with other keywords, it returns same result.
Is there any way to get more than 1000 images?

**Comment by hardikvasa** [comment]
@nauti16 thanks for your feedback. This script downloads all the images that google images returns.

For your search query i am guessing google images just returned 89 image link so the tool was only able to download 89 images. You can verify this by typing the keyword on [google images page](https://images.google.com/).

You can however try to use the `--related_images` argument and it will try and get a lot more images if they are available.

Closing this issue for now. Do let me know if you have any other questions.

**Comment by rjavierch** [comment]
Hi, I have the same problem. I don't think that could be the problem. On my linux laptop I downloaded around 600 images for "Steel beam" and now that I'm downloading new ones for the same name in my windows 7 pc i got 96. I don't know if it is the chrome version.
