### ISSUE TITLE
Safe search?

### ISSUE THREAD

**Issue by BlueTranquility** [hardikvasa/google-images-download#99]
I am looking to integrate this into a project, and I can't have random NSFW pictures appearing. Is there or will there be a way to enable google safesearch?

**Comment by kevinkit** [comment]
I do not think that there is an option. However if you have any other Software installed which normally blocks such websites for you will help you in this case. I tried to download some images and my anti-virus program blocked me from certain websites

**Comment by BlueTranquility** [comment]
Ok, so I don't know if this was a feature, but I just edited the script so that every image was searched with '&safe=active' on the end of the URLs. It now works as hoped.

**Comment by hardikvasa** [comment]
@BlueTranquility thanks for the feature request. I will look into adding this.

**Comment by hardikvasa** [comment]
The new version of the script has this feature. Closing this issue.

Thanks!
